openapi: 3.0.1
info:
  title: CrowdStrike API Specification
  description: |-
    Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and more information about API endpoints that don't yet support OAuth2, see our [documentation inside the Falcon console](https://falcon.us-2.crowdstrike.com/support/documentation).


      To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.us-2.crowdstrike.com`.

      Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.us-2.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
  termsOfService: https://api.us-2.crowdstrike.com/terms
  version: 2022-02-02T19:42:11Z
servers:
  - url: https://api.us-2.crowdstrike.com/
paths:
  /cloud-connect-aws/combined/accounts/v1:
    get:
      tags:
        - cloud-connect-aws
      summary: Search for provisioned AWS Accounts by providing an FQL filter and
        paging details. Returns a set of AWS accounts which match the filter criteria
      operationId: QueryAWSAccounts
      security:
        - oauth2:
            - cloud-connect-aws:read
  /cloud-connect-aws/combined/settings/v1:
    get:
      tags:
        - cloud-connect-aws
      summary: Retrieve a set of Global Settings which are applicable to all provisioned
        AWS accounts
      operationId: GetAWSSettings
      security:
        - oauth2:
            - cloud-connect-aws:read
  /cloud-connect-aws/entities/accounts/v1:
    get:
      tags:
        - cloud-connect-aws
      summary: Retrieve a set of AWS Accounts by specifying their IDs
      operationId: GetAWSAccounts
      security:
        - oauth2:
            - cloud-connect-aws:read
    post:
      tags:
        - cloud-connect-aws
      summary: Provision AWS Accounts by specifying details about the accounts to
        provision
      operationId: ProvisionAWSAccounts
      security:
        - oauth2:
            - cloud-connect-aws:write
    delete:
      tags:
        - cloud-connect-aws
      summary: Delete a set of AWS Accounts by specifying their IDs
      operationId: DeleteAWSAccounts
      security:
        - oauth2:
            - cloud-connect-aws:write
    patch:
      tags:
        - cloud-connect-aws
      summary: Update AWS Accounts by specifying the ID of the account and details
        to update
      operationId: UpdateAWSAccounts
      security:
        - oauth2:
            - cloud-connect-aws:write
  /cloud-connect-aws/entities/settings/v1:
    post:
      tags:
        - cloud-connect-aws
      summary: Create or update Global Settings which are applicable to all provisioned
        AWS accounts
      operationId: CreateOrUpdateAWSSettings
      security:
        - oauth2:
            - cloud-connect-aws:write
  /cloud-connect-aws/entities/verify-account-access/v1:
    post:
      tags:
        - cloud-connect-aws
      summary: Performs an Access Verification check on the specified AWS Account
        IDs
      operationId: VerifyAWSAccountAccess
      security:
        - oauth2:
            - cloud-connect-aws:write
  /cloud-connect-aws/queries/accounts/v1:
    get:
      tags:
        - cloud-connect-aws
      summary: Search for provisioned AWS Accounts by providing an FQL filter and
        paging details. Returns a set of AWS account IDs which match the filter criteria
      operationId: QueryAWSAccountsForIDs
      security:
        - oauth2:
            - cloud-connect-aws:read
  /cloud-connect-azure/entities/account/v1:
    get:
      tags:
        - d4c-registration
      summary: Return information about Azure account registration
      operationId: GetCSPMAzureAccount
      security:
        - oauth2:
            - d4c-registration:read
    post:
      tags:
        - d4c-registration
      summary: Creates a new account in our system for a customer and generates a
        script for them to run in their cloud environment to grant us access.
      operationId: CreateCSPMAzureAccount
      security:
        - oauth2:
            - d4c-registration:write
  /cloud-connect-azure/entities/client-id/v1:
    patch:
      tags:
        - d4c-registration
      summary: Update an Azure service account in our system by with the user-created
        client_id created with the public key we've provided
      operationId: UpdateCSPMAzureAccountClientID
      security:
        - oauth2:
            - d4c-registration:write
  /cloud-connect-azure/entities/user-scripts-download/v1:
    get:
      tags:
        - d4c-registration
      summary: Return a script for customer to run in their cloud environment to grant
        us access to their Azure environment as a downloadable attachment
      operationId: GetCSPMAzureUserScriptsAttachment
      security:
        - oauth2:
            - d4c-registration:read
  /cloud-connect-azure/entities/user-scripts/v1:
    get:
      tags:
        - d4c-registration
      summary: Return a script for customer to run in their cloud environment to grant
        us access to their Azure environment
      operationId: GetCSPMAzureUserScripts
      security:
        - oauth2:
            - d4c-registration:read
  /cloud-connect-cspm-aws/entities/account/v1:
    get:
      tags:
        - cspm-registration
      summary: Returns information about the current status of an AWS account.
      operationId: GetCSPMAwsAccount
      security:
        - oauth2:
            - cspm-registration:read
    post:
      tags:
        - cspm-registration
      summary: Creates a new account in our system for a customer and generates a
        script for them to run in their AWS cloud environment to grant us access.
      operationId: CreateCSPMAwsAccount
      security:
        - oauth2:
            - cspm-registration:write
    delete:
      tags:
        - cspm-registration
      summary: Deletes an existing AWS account or organization in our system.
      operationId: DeleteCSPMAwsAccount
      security:
        - oauth2:
            - cspm-registration:write
    patch:
      tags:
        - cspm-registration
      summary: Patches a existing account in our system for a customer.
      operationId: PatchCSPMAwsAccount
      security:
        - oauth2:
            - cspm-registration:write
  /cloud-connect-cspm-aws/entities/console-setup-urls/v1:
    get:
      tags:
        - cspm-registration
      summary: Return a URL for customer to visit in their cloud environment to grant
        us access to their AWS environment.
      operationId: GetCSPMAwsConsoleSetupURLs
      security:
        - oauth2:
            - cspm-registration:read
  /cloud-connect-cspm-aws/entities/user-scripts-download/v1:
    get:
      tags:
        - cspm-registration
      summary: Return a script for customer to run in their cloud environment to grant
        us access to their AWS environment as a downloadable attachment.
      operationId: GetCSPMAwsAccountScriptsAttachment
      security:
        - oauth2:
            - cspm-registration:read
  /cloud-connect-cspm-azure/entities/account/v1:
    get:
      tags:
        - cspm-registration
      summary: Return information about Azure account registration
      operationId: GetCSPMAzureAccount
      security:
        - oauth2:
            - cspm-registration:read
    post:
      tags:
        - cspm-registration
      summary: Creates a new account in our system for a customer and generates a
        script for them to run in their cloud environment to grant us access.
      operationId: CreateCSPMAzureAccount
      security:
        - oauth2:
            - cspm-registration:write
    delete:
      tags:
        - cspm-registration
      summary: Deletes an Azure subscription from the system.
      operationId: DeleteCSPMAzureAccount
      security:
        - oauth2:
            - cspm-registration:write
  /cloud-connect-cspm-azure/entities/client-id/v1:
    patch:
      tags:
        - cspm-registration
      summary: Update an Azure service account in our system by with the user-created
        client_id created with the public key we've provided
      operationId: UpdateCSPMAzureAccountClientID
      security:
        - oauth2:
            - cspm-registration:write
  /cloud-connect-cspm-azure/entities/default-subscription-id/v1:
    patch:
      tags:
        - cspm-registration
      summary: Update an Azure default subscription_id in our system for given tenant_id
      operationId: UpdateCSPMAzureTenantDefaultSubscriptionID
      security:
        - oauth2:
            - cspm-registration:write
  /cloud-connect-cspm-azure/entities/user-scripts-download/v1:
    get:
      tags:
        - cspm-registration
      summary: Return a script for customer to run in their cloud environment to grant
        us access to their Azure environment as a downloadable attachment
      operationId: GetCSPMAzureUserScriptsAttachment
      security:
        - oauth2:
            - cspm-registration:read
  /cloud-connect-gcp/entities/account/v1:
    get:
      tags:
        - d4c-registration
      summary: Returns information about the current status of an GCP account.
      operationId: GetCSPMCGPAccount
      security:
        - oauth2:
            - d4c-registration:read
    post:
      tags:
        - d4c-registration
      summary: Creates a new account in our system for a customer and generates a
        new service account for them to add access to in their GCP environment to
        grant us access.
      operationId: CreateCSPMGCPAccount
      security:
        - oauth2:
            - d4c-registration:write
  /cloud-connect-gcp/entities/user-scripts-download/v1:
    get:
      tags:
        - d4c-registration
      summary: Return a script for customer to run in their cloud environment to grant
        us access to their GCP environment as a downloadable attachment
      operationId: GetCSPMGCPUserScriptsAttachment
      security:
        - oauth2:
            - d4c-registration:read
  /cloud-connect-gcp/entities/user-scripts/v1:
    get:
      tags:
        - d4c-registration
      summary: Return a script for customer to run in their cloud environment to grant
        us access to their GCP environment
      operationId: GetCSPMGCPUserScripts
      security:
        - oauth2:
            - d4c-registration:read
  /container-security/entities/image-registry-credentials/v1:
    get:
      tags:
        - falcon-container
      summary: Gets the registry credentials
      operationId: GetCredentials
      security:
        - oauth2:
            - falcon-container:read
  /detects/aggregates/detects/GET/v1:
    post:
      tags:
        - detects
      summary: Get detect aggregates as specified via json in request body.
      operationId: GetAggregateDetects
      security:
        - oauth2:
            - detects:read
  /detects/entities/detects/v2:
    patch:
      tags:
        - detects
      summary: Modify the state, assignee, and visibility of detections
      operationId: UpdateDetectsByIdsV2
      security:
        - oauth2:
            - detects:write
  /detects/entities/ioa/v1:
    get:
      tags:
        - cspm-registration
      summary: Get list of detected behaviors
      operationId: GetBehaviorDetections
      security:
        - oauth2:
            - cspm-registration:read
  /detects/entities/iom/v1:
    get:
      tags:
        - cspm-registration
      summary: Get list of active misconfigurations
      operationId: GetConfigurationDetections
      security:
        - oauth2:
            - cspm-registration:read
  /detects/entities/summaries/GET/v1:
    post:
      tags:
        - detects
      summary: View information about detections
      operationId: GetDetectSummaries
      security:
        - oauth2:
            - detects:read
  /detects/queries/detects/v1:
    get:
      tags:
        - detects
      summary: Search for detection IDs that match a given query
      operationId: QueryDetects
      security:
        - oauth2:
            - detects:read
  /devices/combined/devices/login-history/v1:
    post:
      tags:
        - hosts
      summary: Retrieve details about recent login sessions for a set of devices.
      operationId: QueryDeviceLoginHistory
      security:
        - oauth2:
            - devices:read
  /devices/combined/devices/network-address-history/v1:
    post:
      tags:
        - hosts
      summary: Retrieve history of IP and MAC addresses of devices.
      operationId: QueryGetNetworkAddressHistoryV1
      security:
        - oauth2:
            - devices:read
  /devices/combined/host-group-members/v1:
    get:
      tags:
        - host-group
      summary: Search for members of a Host Group in your environment by providing
        an FQL filter and paging details. Returns a set of host details which match
        the filter criteria
      operationId: queryCombinedGroupMembers
      security:
        - oauth2:
            - host-group:read
  /devices/combined/host-groups/v1:
    get:
      tags:
        - host-group
      summary: Search for Host Groups in your environment by providing an FQL filter
        and paging details. Returns a set of Host Groups which match the filter criteria
      operationId: queryCombinedHostGroups
      security:
        - oauth2:
            - host-group:read
  /devices/entities/devices-actions/v2:
    post:
      tags:
        - hosts
      summary: Take various actions on the hosts in your environment. Contain or lift
        containment on a host. Delete or restore a host.
      operationId: PerformActionV2
      security:
        - oauth2:
            - devices:write
  /devices/entities/devices/tags/v1:
    patch:
      tags:
        - hosts
      summary: Append or remove one or more Falcon Grouping Tags on one or more hosts.
      operationId: UpdateDeviceTags
      security:
        - oauth2:
            - devices:write
  /devices/entities/devices/v1:
    get:
      tags:
        - hosts
      summary: Get details on one or more hosts by providing agent IDs (AID). You
        can get a host's agent IDs (AIDs) from the /devices/queries/devices/v1 endpoint,
        the Falcon console or the Streaming API
      operationId: GetDeviceDetails
      security:
        - oauth2:
            - devices:read
  /devices/entities/group-actions/v1:
    post:
      tags:
        - hosts
      summary: Performs the specified action on the provided prevention policy IDs.
      operationId: entities.perform_action
      security:
        - oauth2:
            - devices:write
  /devices/entities/host-group-actions/v1:
    post:
      tags:
        - host-group
      summary: Perform the specified action on the Host Groups specified in the request
      operationId: performGroupAction
      security:
        - oauth2:
            - host-group:write
  /devices/entities/host-groups/v1:
    get:
      tags:
        - host-group
      summary: Retrieve a set of Host Groups by specifying their IDs
      operationId: getHostGroups
      security:
        - oauth2:
            - host-group:read
    post:
      tags:
        - host-group
      summary: Create Host Groups by specifying details about the group to create
      operationId: createHostGroups
      security:
        - oauth2:
            - host-group:write
    delete:
      tags:
        - host-group
      summary: Delete a set of Host Groups by specifying their IDs
      operationId: deleteHostGroups
      security:
        - oauth2:
            - host-group:write
    patch:
      tags:
        - host-group
      summary: Update Host Groups by specifying the ID of the group and details to
        update
      operationId: updateHostGroups
      security:
        - oauth2:
            - host-group:write
  /devices/queries/devices-hidden/v1:
    get:
      tags:
        - hosts
      summary: Retrieve hidden hosts that match the provided filter criteria.
      operationId: QueryHiddenDevices
      security:
        - oauth2:
            - devices:read
  /devices/queries/devices-scroll/v1:
    get:
      tags:
        - hosts
      summary: Search for hosts in your environment by platform, hostname, IP, and
        other criteria with continuous pagination capability (based on offset pointer
        which expires after 2 minutes with no maximum limit)
      operationId: QueryDevicesByFilterScroll
      security:
        - oauth2:
            - devices:read
  /devices/queries/devices/v1:
    get:
      tags:
        - hosts
      summary: Search for hosts in your environment by platform, hostname, IP, and
        other criteria.
      operationId: QueryDevicesByFilter
      security:
        - oauth2:
            - devices:read
  /devices/queries/host-group-members/v1:
    get:
      tags:
        - host-group
      summary: Search for members of a Host Group in your environment by providing
        an FQL filter and paging details. Returns a set of Agent IDs which match the
        filter criteria
      operationId: queryGroupMembers
      security:
        - oauth2:
            - host-group:read
  /devices/queries/host-groups/v1:
    get:
      tags:
        - host-group
      summary: Search for Host Groups in your environment by providing an FQL filter
        and paging details. Returns a set of Host Group IDs which match the filter
        criteria
      operationId: queryHostGroups
      security:
        - oauth2:
            - host-group:read
  /discover/entities/hosts/v1:
    get:
      tags:
        - discover
      summary: Get details on assets by providing one or more IDs.
      operationId: get-hosts
      security:
        - oauth2:
            - discover:read
  /discover/queries/hosts/v1:
    get:
      tags:
        - discover
      summary: Search for assets in your environment by providing an FQL (Falcon Query
        Language) filter and paging details. Returns a set of asset IDs which match
        the filter criteria.
      operationId: query-hosts
      security:
        - oauth2:
            - discover:read
  /falcon-complete-dashboards/aggregates/allowlist/GET/v1:
    post:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve aggregate allowlist ticket values based on the matched filter
      operationId: AggregateAllowList
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/aggregates/blocklist/GET/v1:
    post:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve aggregate blocklist ticket values based on the matched filter
      operationId: AggregateBlockList
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/aggregates/detects/GET/v1:
    post:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve aggregate detection values based on the matched filter
      operationId: AggregateDetections
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/aggregates/devicecount-collections/GET/v1:
    post:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve aggregate host/devices count based on the matched filter
      operationId: AggregateDeviceCountCollection
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/aggregates/escalations/GET/v1:
    post:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve aggregate escalation ticket values based on the matched filter
      operationId: AggregateEscalations
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/aggregates/incidents/GET/v1:
    post:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve aggregate incident values based on the matched filter
      operationId: AggregateFCIncidents
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/aggregates/remediations/GET/v1:
    post:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve aggregate remediation ticket values based on the matched filter
      operationId: AggregateRemediations
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/queries/allowlist/v1:
    get:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve allowlist tickets that match the provided filter criteria
        with scrolling enabled
      operationId: QueryAllowListFilter
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/queries/blocklist/v1:
    get:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve block listtickets that match the provided filter criteria
        with scrolling enabled
      operationId: QueryBlockListFilter
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/queries/detects/v1:
    get:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve DetectionsIds that match the provided FQL filter, criteria
        with scrolling enabled
      operationId: QueryDetectionIdsByFilter
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/queries/devicecount-collections/v1:
    get:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve device count collection Ids that match the provided FQL filter,
        criteria with scrolling enabled
      operationId: GetDeviceCountCollectionQueriesByFilter
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/queries/escalations/v1:
    get:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve escalation tickets that match the provided filter criteria
        with scrolling enabled
      operationId: QueryEscalationsFilter
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/queries/incidents/v1:
    get:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve incidents that match the provided filter criteria with scrolling
        enabled
      operationId: QueryIncidentIdsByFilter
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falcon-complete-dashboards/queries/remediations/v1:
    get:
      tags:
        - Falcon Complete Dashboard
      summary: Retrieve remediation tickets that match the provided filter criteria
        with scrolling enabled
      operationId: QueryRemediationsFilter
      security:
        - oauth2:
            - falconcomplete-dashboard:read
  /falconx/entities/artifacts/v1:
    get:
      tags:
        - falconx-sandbox
      summary: Download IOC packs, PCAP files, and other analysis artifacts.
      operationId: GetArtifacts
      security:
        - oauth2:
            - falconx-sandbox:read
  /falconx/entities/report-summaries/v1:
    get:
      tags:
        - falconx-sandbox
      summary: Get a short summary version of a sandbox report.
      operationId: GetSummaryReports
      security:
        - oauth2:
            - falconx-sandbox:read
  /falconx/entities/reports/v1:
    get:
      tags:
        - falconx-sandbox
      summary: Get a full sandbox report.
      operationId: GetReports
      security:
        - oauth2:
            - falconx-sandbox:read
    delete:
      tags:
        - falconx-sandbox
      summary: Delete report based on the report ID. Operation can be checked for
        success by polling for the report ID on the report-summaries endpoint.
      operationId: DeleteReport
      security:
        - oauth2:
            - falconx-sandbox:write
  /falconx/entities/submissions/v1:
    get:
      tags:
        - falconx-sandbox
      summary: Check the status of a sandbox analysis. Time required for analysis
        varies but is usually less than 15 minutes.
      operationId: GetSubmissions
      security:
        - oauth2:
            - falconx-sandbox:read
    post:
      tags:
        - falconx-sandbox
      summary: Submit an uploaded file or a URL for sandbox analysis. Time required
        for analysis varies but is usually less than 15 minutes.
      operationId: Submit
      security:
        - oauth2:
            - falconx-sandbox:write
  /falconx/queries/reports/v1:
    get:
      tags:
        - falconx-sandbox
      summary: Find sandbox reports by providing an FQL filter and paging details.
        Returns a set of report IDs that match your criteria.
      operationId: QueryReports
      security:
        - oauth2:
            - falconx-sandbox:read
  /falconx/queries/submissions/v1:
    get:
      tags:
        - falconx-sandbox
      summary: Find submission IDs for uploaded files by providing an FQL filter and
        paging details. Returns a set of submission IDs that match your criteria.
      operationId: QuerySubmissionsMixin0
      security:
        - oauth2:
            - falconx-sandbox:read
  /filevantage/entities/changes/v2:
    get:
      tags:
        - filevantage
      summary: Retrieve information on changes
      description: Retrieve key attributes of Falcon FileVantage changes for the specified
        ids.
      operationId: getChanges
      security:
        - oauth2:
            - fim:read
  /filevantage/queries/changes/v2:
    get:
      tags:
        - filevantage
      summary: Returns one or more change IDs
      description: Returns a list of Falcon FileVantage change IDs filtered, sorted
        and limited by the query parameters provided
      operationId: queryChanges
      security:
        - oauth2:
            - fim:read
  /fwmgr/aggregates/events/GET/v1:
    post:
      tags:
        - firewall-management
      summary: Aggregate events for customer
      operationId: aggregate-events
      security:
        - oauth2:
            - firewall-management:write
  /fwmgr/aggregates/policy-rules/GET/v1:
    post:
      tags:
        - firewall-management
      summary: Aggregate rules within a policy for customer
      operationId: aggregate-policy-rules
      security:
        - oauth2:
            - firewall-management:write
  /fwmgr/aggregates/rule-groups/GET/v1:
    post:
      tags:
        - firewall-management
      summary: Aggregate rule groups for customer
      operationId: aggregate-rule-groups
      security:
        - oauth2:
            - firewall-management:write
  /fwmgr/aggregates/rules/GET/v1:
    post:
      tags:
        - firewall-management
      summary: Aggregate rules for customer
      operationId: aggregate-rules
      security:
        - oauth2:
            - firewall-management:write
  /fwmgr/entities/events/v1:
    get:
      tags:
        - firewall-management
      summary: Get events entities by ID and optionally version
      operationId: get-events
      security:
        - oauth2:
            - firewall-management:read
  /fwmgr/entities/firewall-fields/v1:
    get:
      tags:
        - firewall-management
      summary: Get the firewall field specifications by ID
      operationId: get-firewall-fields
      security:
        - oauth2:
            - firewall-management:read
  /fwmgr/entities/platforms/v1:
    get:
      tags:
        - firewall-management
      summary: Get platforms by ID, e.g., windows or mac or droid
      operationId: get-platforms
      security:
        - oauth2:
            - firewall-management:read
  /fwmgr/entities/policies/v1:
    get:
      tags:
        - firewall-management
      summary: Get policy container entities by policy ID
      operationId: get-policy-containers
      security:
        - oauth2:
            - firewall-management:read
    put:
      tags:
        - firewall-management
      summary: Update an identified policy container
      operationId: update-policy-container
      security:
        - oauth2:
            - firewall-management:write
  /fwmgr/entities/rule-groups/v1:
    get:
      tags:
        - firewall-management
      summary: Get rule group entities by ID. These groups do not contain their rule
        entites, just the rule IDs in precedence order.
      operationId: get-rule-groups
      security:
        - oauth2:
            - firewall-management:read
    post:
      tags:
        - firewall-management
      summary: Create new rule group on a platform for a customer with a name and
        description, and return the ID
      operationId: create-rule-group
      security:
        - oauth2:
            - firewall-management:write
    delete:
      tags:
        - firewall-management
      summary: Delete rule group entities by ID
      operationId: delete-rule-groups
      security:
        - oauth2:
            - firewall-management:write
    patch:
      tags:
        - firewall-management
      summary: Update name, description, or enabled status of a rule group, or create,
        edit, delete, or reorder rules
      operationId: update-rule-group
      security:
        - oauth2:
            - firewall-management:write
  /fwmgr/entities/rules/v1:
    get:
      tags:
        - firewall-management
      summary: Get rule entities by ID (64-bit unsigned int as decimal string) or
        Family ID (32-character hexadecimal string)
      operationId: get-rules
      security:
        - oauth2:
            - firewall-management:read
  /fwmgr/queries/events/v1:
    get:
      tags:
        - firewall-management
      summary: Find all event IDs matching the query with filter
      operationId: query-events
      security:
        - oauth2:
            - firewall-management:read
  /fwmgr/queries/firewall-fields/v1:
    get:
      tags:
        - firewall-management
      summary: Get the firewall field specification IDs for the provided platform
      operationId: query-firewall-fields
      security:
        - oauth2:
            - firewall-management:read
  /fwmgr/queries/platforms/v1:
    get:
      tags:
        - firewall-management
      summary: Get the list of platform names
      operationId: query-platforms
      security:
        - oauth2:
            - firewall-management:read
  /fwmgr/queries/policy-rules/v1:
    get:
      tags:
        - firewall-management
      summary: Find all firewall rule IDs matching the query with filter, and return
        them in precedence order
      operationId: query-policy-rules
      security:
        - oauth2:
            - firewall-management:read
  /fwmgr/queries/rule-groups/v1:
    get:
      tags:
        - firewall-management
      summary: Find all rule group IDs matching the query with filter
      operationId: query-rule-groups
      security:
        - oauth2:
            - firewall-management:read
  /fwmgr/queries/rules/v1:
    get:
      tags:
        - firewall-management
      summary: Find all rule IDs matching the query with filter
      operationId: query-rules
      security:
        - oauth2:
            - firewall-management:read
  /identity-protection/combined/graphql/v1:
    post:
      tags:
        - identity-protection
      summary: Identity Protection GraphQL API. Allows to retrieve entities, timeline
        activities, identity-based incidents and security assessment. Allows to perform
        actions on entities and identity-based incidents.
      operationId: api.preempt.proxy.post.graphql
      security:
        - oauth2:
            - identity-graphql:write
      x-cs-exposures:
        - public
      x-cs-ingress-name: service
      x-cs-microservice-id: 194
      x-cs-microservice-name: cs.preemptgateway
      x-cs-namespace: identity-graphql
      x-cs-service-host: https://cspreemptgateway-pool-main.gyr.mav.eyrie.cloud
      x-cs-service-key: cspreemptgateway
      x-cs-service-port: 443
      x-cs-service-role: cspreemptgateway
  /incidents/combined/crowdscores/v1:
    get:
      tags:
        - incidents
      summary: Query environment wide CrowdScore and return the entity data
      operationId: CrowdScore
      security:
        - oauth2:
            - incidents:read
  /incidents/entities/behaviors/GET/v1:
    post:
      tags:
        - incidents
      summary: Get details on behaviors by providing behavior IDs
      operationId: GetBehaviors
      security:
        - oauth2:
            - incidents:read
  /incidents/entities/incident-actions/v1:
    post:
      tags:
        - incidents
      summary: Perform a set of actions on one or more incidents, such as adding tags
        or comments or updating the incident name or description
      operationId: PerformIncidentAction
      security:
        - oauth2:
            - incidents:write
  /incidents/entities/incidents/GET/v1:
    post:
      tags:
        - incidents
      summary: Get details on incidents by providing incident IDs
      operationId: GetIncidents
      security:
        - oauth2:
            - incidents:read
  /incidents/queries/behaviors/v1:
    get:
      tags:
        - incidents
      summary: Search for behaviors by providing an FQL filter, sorting, and paging
        details
      operationId: QueryBehaviors
      security:
        - oauth2:
            - incidents:read
  /incidents/queries/incidents/v1:
    get:
      tags:
        - incidents
      summary: Search for incidents by providing an FQL filter, sorting, and paging
        details
      operationId: QueryIncidents
      security:
        - oauth2:
            - incidents:read
  /indicators/aggregates/devices-count/v1:
    get:
      tags:
        - iocs
      summary: Number of hosts in your customer account that have observed a given
        custom IOC
      operationId: DevicesCount
      security:
        - oauth2:
            - iocs:read
  /indicators/queries/devices/v1:
    get:
      tags:
        - iocs
      summary: Find hosts that have observed a given custom IOC. For details about
        those hosts, use GET /devices/entities/devices/v1
      operationId: DevicesRanOn
      security:
        - oauth2:
            - iocs:read
  /indicators/queries/processes/v1:
    get:
      tags:
        - iocs
      summary: Search for processes associated with a custom IOC
      operationId: ProcessesRanOn
      security:
        - oauth2:
            - iocs:read
  /installation-tokens/entities/audit-events/v1:
    get:
      tags:
        - installation-tokens
      summary: Gets the details of one or more audit events by id.
      operationId: audit-events-read
      security:
        - oauth2:
            - installation-tokens:read
  /installation-tokens/entities/customer-settings/v1:
    get:
      tags:
        - installation-tokens
      summary: Check current installation token settings.
      operationId: customer-settings-read
      security:
        - oauth2:
            - installation-tokens:read
  /installation-tokens/entities/tokens/v1:
    get:
      tags:
        - installation-tokens
      summary: Gets the details of one or more tokens by id.
      operationId: tokens-read
      security:
        - oauth2:
            - installation-tokens:read
    post:
      tags:
        - installation-tokens
      summary: Creates a token.
      operationId: tokens-create
      security:
        - oauth2:
            - installation-tokens:write
    delete:
      tags:
        - installation-tokens
      summary: Deletes a token immediately. To revoke a token, use PATCH /installation-tokens/entities/tokens/v1
        instead.
      operationId: tokens-delete
      security:
        - oauth2:
            - installation-tokens:write
    patch:
      tags:
        - installation-tokens
      summary: Updates one or more tokens. Use this endpoint to edit labels, change
        expiration, revoke, or restore.
      operationId: tokens-update
      security:
        - oauth2:
            - installation-tokens:write
  /installation-tokens/queries/audit-events/v1:
    get:
      tags:
        - installation-tokens
      summary: Search for audit events by providing an FQL filter and paging details.
      operationId: audit-events-query
      security:
        - oauth2:
            - installation-tokens:read
  /installation-tokens/queries/tokens/v1:
    get:
      tags:
        - installation-tokens
      summary: Search for tokens by providing an FQL filter and paging details.
      operationId: tokens-query
      security:
        - oauth2:
            - installation-tokens:read
  /intel/combined/actors/v1:
    get:
      tags:
        - intel
      summary: Get info about actors that match provided FQL filters.
      operationId: QueryIntelActorEntities
      security:
        - oauth2:
            - falconx-actors:read
  /intel/combined/indicators/v1:
    get:
      tags:
        - intel
      summary: Get info about indicators that match provided FQL filters.
      operationId: QueryIntelIndicatorEntities
      security:
        - oauth2:
            - falconx-indicators:read
  /intel/combined/reports/v1:
    get:
      tags:
        - intel
      summary: Get info about reports that match provided FQL filters.
      operationId: QueryIntelReportEntities
      security:
        - oauth2:
            - falconx-reports:read
  /intel/entities/actors/v1:
    get:
      tags:
        - intel
      summary: Retrieve specific actors using their actor IDs.
      operationId: GetIntelActorEntities
      security:
        - oauth2:
            - falconx-actors:read
  /intel/entities/indicators/GET/v1:
    post:
      tags:
        - intel
      summary: Retrieve specific indicators using their indicator IDs.
      operationId: GetIntelIndicatorEntities
      security:
        - oauth2:
            - falconx-indicators:read
  /intel/entities/report-files/v1:
    get:
      tags:
        - intel
      summary: Return a Report PDF attachment
      operationId: GetIntelReportPDF
      security:
        - oauth2:
            - falconx-reports:read
  /intel/entities/reports/v1:
    get:
      tags:
        - intel
      summary: Retrieve specific reports using their report IDs.
      operationId: GetIntelReportEntities
      security:
        - oauth2:
            - falconx-reports:read
  /intel/entities/rules-files/v1:
    get:
      tags:
        - intel
      summary: Download earlier rule sets.
      operationId: GetIntelRuleFile
      security:
        - oauth2:
            - falconx-rules:read
  /intel/entities/rules-latest-files/v1:
    get:
      tags:
        - intel
      summary: Download the latest rule set.
      operationId: GetLatestIntelRuleFile
      security:
        - oauth2:
            - falconx-rules:read
  /intel/entities/rules/v1:
    get:
      tags:
        - intel
      summary: Retrieve details for rule sets for the specified ids.
      operationId: GetIntelRuleEntities
      security:
        - oauth2:
            - falconx-rules:read
  /intel/queries/actors/v1:
    get:
      tags:
        - intel
      summary: Get actor IDs that match provided FQL filters.
      operationId: QueryIntelActorIds
      security:
        - oauth2:
            - falconx-actors:read
  /intel/queries/indicators/v1:
    get:
      tags:
        - intel
      summary: Get indicators IDs that match provided FQL filters.
      operationId: QueryIntelIndicatorIds
      security:
        - oauth2:
            - falconx-indicators:read
  /intel/queries/reports/v1:
    get:
      tags:
        - intel
      summary: Get report IDs that match provided FQL filters.
      operationId: QueryIntelReportIds
      security:
        - oauth2:
            - falconx-reports:read
  /intel/queries/rules/v1:
    get:
      tags:
        - intel
      summary: Search for rule IDs that match provided filter criteria.
      operationId: QueryIntelRuleIds
      security:
        - oauth2:
            - falconx-rules:read
  /ioa/entities/events/v1:
    get:
      tags:
        - cspm-registration
      summary: For CSPM IOA events, gets list of IOA events.
      operationId: GetIOAEvents
      security:
        - oauth2:
            - cspm-registration:read
  /ioa/entities/users/v1:
    get:
      tags:
        - cspm-registration
      summary: For CSPM IOA users, gets list of IOA users.
      operationId: GetIOAUsers
      security:
        - oauth2:
            - cspm-registration:read
  /ioarules/entities/pattern-severities/v1:
    get:
      tags:
        - custom-ioa
      summary: Get pattern severities by ID.
      operationId: get-patterns
      security:
        - oauth2:
            - custom-ioa:read
  /ioarules/entities/platforms/v1:
    get:
      tags:
        - custom-ioa
      summary: Get platforms by ID.
      operationId: get-platformsMixin0
      security:
        - oauth2:
            - custom-ioa:read
  /ioarules/entities/rule-groups/v1:
    get:
      tags:
        - custom-ioa
      summary: Get rule groups by ID.
      operationId: get-rule-groupsMixin0
      security:
        - oauth2:
            - custom-ioa:read
    post:
      tags:
        - custom-ioa
      summary: Create a rule group for a platform with a name and an optional description.
        Returns the rule group.
      operationId: create-rule-groupMixin0
      security:
        - oauth2:
            - custom-ioa:write
    delete:
      tags:
        - custom-ioa
      summary: Delete rule groups by ID.
      operationId: delete-rule-groupsMixin0
      security:
        - oauth2:
            - custom-ioa:write
    patch:
      tags:
        - custom-ioa
      summary: 'Update a rule group. The following properties can be modified: name,
        description, enabled.'
      operationId: update-rule-groupMixin0
      security:
        - oauth2:
            - custom-ioa:write
  /ioarules/entities/rule-types/v1:
    get:
      tags:
        - custom-ioa
      summary: Get rule types by ID.
      operationId: get-rule-types
      security:
        - oauth2:
            - custom-ioa:read
  /ioarules/entities/rules/GET/v1:
    post:
      tags:
        - custom-ioa
      summary: 'Get rules by ID and optionally version in the following format: `ID[:version]`.'
      operationId: get-rules-get
      security:
        - oauth2:
            - custom-ioa:write
  /ioarules/entities/rules/v1:
    get:
      tags:
        - custom-ioa
      summary: 'Get rules by ID and optionally version in the following format: `ID[:version]`.
        The max number of IDs is constrained by URL size.'
      operationId: get-rulesMixin0
      security:
        - oauth2:
            - custom-ioa:read
    post:
      tags:
        - custom-ioa
      summary: Create a rule within a rule group. Returns the rule.
      operationId: create-rule
      security:
        - oauth2:
            - custom-ioa:write
    delete:
      tags:
        - custom-ioa
      summary: Delete rules from a rule group by ID.
      operationId: delete-rules
      security:
        - oauth2:
            - custom-ioa:write
    patch:
      tags:
        - custom-ioa
      summary: Update rules within a rule group. Return the updated rules.
      operationId: update-rules
      security:
        - oauth2:
            - custom-ioa:write
  /ioarules/entities/rules/validate/v1:
    post:
      tags:
        - custom-ioa
      summary: Validates field values and checks for matches if a test string is provided.
      operationId: validate
      security:
        - oauth2:
            - custom-ioa:write
  /ioarules/queries/pattern-severities/v1:
    get:
      tags:
        - custom-ioa
      summary: Get all pattern severity IDs.
      operationId: query-patterns
      security:
        - oauth2:
            - custom-ioa:read
  /ioarules/queries/platforms/v1:
    get:
      tags:
        - custom-ioa
      summary: Get all platform IDs.
      operationId: query-platformsMixin0
      security:
        - oauth2:
            - custom-ioa:read
  /ioarules/queries/rule-groups-full/v1:
    get:
      tags:
        - custom-ioa
      summary: Find all rule groups matching the query with optional filter.
      operationId: query-rule-groups-full
      security:
        - oauth2:
            - custom-ioa:read
  /ioarules/queries/rule-groups/v1:
    get:
      tags:
        - custom-ioa
      summary: Finds all rule group IDs matching the query with optional filter.
      operationId: query-rule-groupsMixin0
      security:
        - oauth2:
            - custom-ioa:read
  /ioarules/queries/rule-types/v1:
    get:
      tags:
        - custom-ioa
      summary: Get all rule type IDs.
      operationId: query-rule-types
      security:
        - oauth2:
            - custom-ioa:read
  /ioarules/queries/rules/v1:
    get:
      tags:
        - custom-ioa
      summary: Finds all rule IDs matching the query with optional filter.
      operationId: query-rulesMixin0
      security:
        - oauth2:
            - custom-ioa:read
  /iocs/combined/indicator/v1:
    get:
      tags:
        - ioc
      summary: Get Combined for Indicators.
      operationId: indicator.combined.v1
      security:
        - oauth2:
            - ioc:read
  /iocs/entities/indicators/v1:
    get:
      tags:
        - ioc
      summary: Get Indicators by ids.
      operationId: indicator.get.v1
      security:
        - oauth2:
            - ioc:read
    post:
      tags:
        - ioc
      summary: Create Indicators.
      operationId: indicator.create.v1
      security:
        - oauth2:
            - ioc:write
    delete:
      tags:
        - ioc
      summary: Delete Indicators by ids.
      operationId: indicator.delete.v1
      security:
        - oauth2:
            - ioc:write
    patch:
      tags:
        - ioc
      summary: Update Indicators.
      operationId: indicator.update.v1
      security:
        - oauth2:
            - ioc:write
  /iocs/queries/indicators/v1:
    get:
      tags:
        - ioc
      summary: Search for Indicators.
      operationId: indicator.search.v1
      security:
        - oauth2:
            - ioc:read
  /kubernetes-protection/entities/accounts/aws/v1:
    get:
      tags:
        - kubernetes-protection
      summary: Provides a list of AWS accounts.
      operationId: GetAWSAccountsMixin0
      security:
        - oauth2:
            - kubernetes-protection:read
    post:
      tags:
        - kubernetes-protection
      summary: Creates a new AWS account in our system for a customer and generates
        the installation script
      operationId: CreateAWSAccount
      security:
        - oauth2:
            - kubernetes-protection:write
    delete:
      tags:
        - kubernetes-protection
      summary: Delete AWS accounts.
      operationId: DeleteAWSAccountsMixin0
      security:
        - oauth2:
            - kubernetes-protection:write
    patch:
      tags:
        - kubernetes-protection
      summary: Updates the AWS account per the query parameters provided
      operationId: UpdateAWSAccount
      security:
        - oauth2:
            - kubernetes-protection:write
  /kubernetes-protection/entities/cloud-locations/v1:
    get:
      tags:
        - kubernetes-protection
      summary: Provides the cloud locations acknowledged by the Kubernetes Protection
        service
      operationId: GetLocations
      security:
        - oauth2:
            - kubernetes-protection:read
  /kubernetes-protection/entities/integration/agent/v1:
    get:
      tags:
        - kubernetes-protection
      summary: Provides a sample Helm values.yaml file for a customer to install alongside
        the agent Helm chart
      operationId: GetHelmValuesYaml
      security:
        - oauth2:
            - kubernetes-protection:read
  /kubernetes-protection/entities/integration/api-key/v1:
    post:
      tags:
        - kubernetes-protection
      summary: Regenerate API key for docker registry integrations
      operationId: RegenerateAPIKey
      security:
        - oauth2:
            - kubernetes-protection:write
  /kubernetes-protection/entities/kubernetes/clusters/v1:
    get:
      tags:
        - kubernetes-protection
      summary: Provides the clusters acknowledged by the Kubernetes Protection service
      operationId: GetClusters
      security:
        - oauth2:
            - kubernetes-protection:read
  /kubernetes-protection/entities/scan/trigger/v1:
    post:
      tags:
        - kubernetes-protection
      summary: Triggers a dry run or a full scan of a customer's kubernetes footprint
      operationId: TriggerScan
      security:
        - oauth2:
            - kubernetes-protection:write
  /malquery/aggregates/quotas/v1:
    get:
      tags:
        - malquery
      summary: Get information about search and download quotas in your environment
      operationId: GetMalQueryQuotasV1
      security:
        - oauth2:
            - malquery:read
  /malquery/combined/fuzzy-search/v1:
    post:
      tags:
        - malquery
      summary: Search Falcon MalQuery quickly, but with more potential for false positives.
        Search for a combination of hex patterns and strings in order to identify
        samples based upon file content at byte level granularity.
      operationId: PostMalQueryFuzzySearchV1
      security:
        - oauth2:
            - malquery:write
  /malquery/entities/download-files/v1:
    get:
      tags:
        - malquery
      summary: Download a file indexed by MalQuery. Specify the file using its SHA256.
        Only one file is supported at this time
      operationId: GetMalQueryDownloadV1
      security:
        - oauth2:
            - malquery:read
  /malquery/entities/metadata/v1:
    get:
      tags:
        - malquery
      summary: Retrieve indexed files metadata by their hash
      operationId: GetMalQueryMetadataV1
      security:
        - oauth2:
            - malquery:read
  /malquery/entities/requests/v1:
    get:
      tags:
        - malquery
      summary: Check the status and results of an asynchronous request, such as hunt
        or exact-search. Supports a single request id at this time.
      operationId: GetMalQueryRequestV1
      security:
        - oauth2:
            - malquery:read
  /malquery/entities/samples-fetch/v1:
    get:
      tags:
        - malquery
      summary: Fetch a zip archive with password 'infected' containing the samples.
        Call this once the /entities/samples-multidownload request has finished processing
      operationId: GetMalQueryEntitiesSamplesFetchV1
      security:
        - oauth2:
            - malquery:read
  /malquery/entities/samples-multidownload/v1:
    post:
      tags:
        - malquery
      summary: Schedule samples for download. Use the result id with the /request
        endpoint to check if the download is ready after which you can call the /entities/samples-fetch
        to get the zip
      operationId: PostMalQueryEntitiesSamplesMultidownloadV1
      security:
        - oauth2:
            - malquery:write
  /malquery/queries/exact-search/v1:
    post:
      tags:
        - malquery
      summary: Search Falcon MalQuery for a combination of hex patterns and strings
        in order to identify samples based upon file content at byte level granularity.
        You can filter results on criteria such as file type, file size and first
        seen date. Returns a request id which can be used with the /request endpoint
      operationId: PostMalQueryExactSearchV1
      security:
        - oauth2:
            - malquery:write
  /malquery/queries/hunt/v1:
    post:
      tags:
        - malquery
      summary: Schedule a YARA-based search for execution. Returns a request id which
        can be used with the /request endpoint
      operationId: PostMalQueryHuntV1
      security:
        - oauth2:
            - malquery:write
  /message-center/aggregates/cases/GET/v1:
    post:
      tags:
        - message-center
      summary: Retrieve aggregate case values based on the matched filter
      operationId: AggregateCases
      security:
        - oauth2:
            - message-center:read
  /message-center/entities/case-activities/GET/v1:
    post:
      tags:
        - message-center
      summary: Retrieve activities for given id's
      operationId: GetCaseActivityByIds
      security:
        - oauth2:
            - message-center:read
  /message-center/entities/case-activity/v1:
    post:
      tags:
        - message-center
      summary: Add an activity to case. Only activities of type comment are allowed
        via API
      operationId: CaseAddActivity
      security:
        - oauth2:
            - message-center:write
  /message-center/entities/case-attachment/v1:
    get:
      tags:
        - message-center
      summary: retrieves an attachment for the case, given the attachment id
      operationId: CaseDownloadAttachment
      security:
        - oauth2:
            - message-center:read
    post:
      tags:
        - message-center
      summary: Upload an attachment for the case.
      description: "Upload an attachment for the case. Maximum upload size allowed\
        \ is *15 MB*.\n\n Filename must start with *[a-zA-Z0-9_-]*. Allowed characters\
        \ in file name are *[a-zA-Z0-9-_.\\s]*. \n\n Maximum file name is *255* characters\
        \ \n\n\n\n Following attachment types are allowed: \n\n- png \n\n- bmp \n\n\
        - jpg \n\n- jpeg \n\n- gif \n\n- pdf \n\n- doc \n\n- docx \n\n- xls \n\n-\
        \ xlsx \n\n- pptx \n\n- txt \n\n- csv"
      operationId: CaseAddAttachment
      security:
        - oauth2:
            - message-center:write
  /message-center/entities/case/v1:
    post:
      tags:
        - message-center
      summary: create a new case
      operationId: CreateCase
      security:
        - oauth2:
            - message-center:write
    patch:
      tags:
        - message-center
      summary: update an existing case
      operationId: UpdateCase
      security:
        - oauth2:
            - message-center:write
  /message-center/entities/cases/GET/v1:
    post:
      tags:
        - message-center
      summary: Retrieve message center cases
      operationId: GetCaseEntitiesByIDs
      security:
        - oauth2:
            - message-center:read
  /message-center/queries/case-activities/v1:
    get:
      tags:
        - message-center
      summary: Retrieve activities id's for a case
      operationId: QueryActivityByCaseID
      security:
        - oauth2:
            - message-center:read
  /message-center/queries/cases/v1:
    get:
      tags:
        - message-center
      summary: Retrieve case id's that match the provided filter criteria
      operationId: QueryCasesIdsByFilter
      security:
        - oauth2:
            - message-center:read
  /mssp/entities/children/v1:
    get:
      tags:
        - mssp
      summary: Get link to child customer by child CID(s)
      operationId: getChildren
      security:
        - oauth2:
            - mssp:read
  /mssp/entities/cid-group-members/v1:
    get:
      tags:
        - mssp
      summary: Get CID group members by CID group ID.
      operationId: getCIDGroupMembersBy
      security:
        - oauth2:
            - mssp:read
    post:
      tags:
        - mssp
      summary: Add new CID Group member.
      operationId: addCIDGroupMembers
      security:
        - oauth2:
            - mssp:write
    delete:
      tags:
        - mssp
      summary: Delete CID Group members entry.
      operationId: deleteCIDGroupMembers
      security:
        - oauth2:
            - mssp:write
  /mssp/entities/cid-groups/v1:
    get:
      tags:
        - mssp
      summary: Get CID groups by ID.
      operationId: getCIDGroupById
      security:
        - oauth2:
            - mssp:read
    post:
      tags:
        - mssp
      summary: Create new CID Group(s). Maximum 500 CID Group(s) allowed.
      operationId: createCIDGroups
      security:
        - oauth2:
            - mssp:write
    delete:
      tags:
        - mssp
      summary: Delete CID groups by ID.
      operationId: deleteCIDGroups
      security:
        - oauth2:
            - mssp:write
    patch:
      tags:
        - mssp
      summary: Update existing CID Group(s). CID Group ID is expected for each CID
        Group definition provided in request body. CID Group member(s) remain unaffected.
      operationId: updateCIDGroups
      security:
        - oauth2:
            - mssp:write
  /mssp/entities/mssp-roles/v1:
    get:
      tags:
        - mssp
      summary: Get MSSP Role assignment(s). MSSP Role assignment is of the format
        :.
      operationId: getRolesByID
      security:
        - oauth2:
            - mssp:read
    post:
      tags:
        - mssp
      summary: 'Assign new MSSP Role(s) between User Group and CID Group. It does
        not revoke existing role(s) between User Group and CID Group. User Group ID
        and CID Group ID have to be specified in request. '
      operationId: addRole
      security:
        - oauth2:
            - mssp:write
    delete:
      tags:
        - mssp
      summary: Delete MSSP Role assignment(s) between User Group and CID Group. User
        Group ID and CID Group ID have to be specified in request. Only specified
        roles are removed if specified in request payload, else association between
        User Group and CID Group is dissolved completely (if no roles specified).
      operationId: deletedRoles
      security:
        - oauth2:
            - mssp:write
  /mssp/entities/user-group-members/v1:
    get:
      tags:
        - mssp
      summary: Get user group members by user group ID.
      operationId: getUserGroupMembersByID
      security:
        - oauth2:
            - mssp:read
    post:
      tags:
        - mssp
      summary: Add new User Group member. Maximum 500 members allowed per User Group.
      operationId: addUserGroupMembers
      security:
        - oauth2:
            - mssp:write
    delete:
      tags:
        - mssp
      summary: Delete User Group members entry.
      operationId: deleteUserGroupMembers
      security:
        - oauth2:
            - mssp:write
  /mssp/entities/user-groups/v1:
    get:
      tags:
        - mssp
      summary: Get user groups by ID.
      operationId: getUserGroupsByID
      security:
        - oauth2:
            - mssp:read
    post:
      tags:
        - mssp
      summary: Create new User Group(s). Maximum 500 User Group(s) allowed per customer.
      operationId: createUserGroups
      security:
        - oauth2:
            - mssp:write
    delete:
      tags:
        - mssp
      summary: Delete user groups by ID.
      operationId: deleteUserGroups
      security:
        - oauth2:
            - mssp:write
    patch:
      tags:
        - mssp
      summary: Update existing User Group(s). User Group ID is expected for each User
        Group definition provided in request body. User Group member(s) remain unaffected.
      operationId: updateUserGroups
      security:
        - oauth2:
            - mssp:write
  /mssp/queries/children/v1:
    get:
      tags:
        - mssp
      summary: Query for customers linked as children
      operationId: queryChildren
      security:
        - oauth2:
            - mssp:read
  /mssp/queries/cid-group-members/v1:
    get:
      tags:
        - mssp
      summary: Query a CID groups members by associated CID.
      operationId: queryCIDGroupMembers
      security:
        - oauth2:
            - mssp:read
  /mssp/queries/cid-groups/v1:
    get:
      tags:
        - mssp
      summary: Query CID Groups.
      operationId: queryCIDGroups
      security:
        - oauth2:
            - mssp:read
  /mssp/queries/mssp-roles/v1:
    get:
      tags:
        - mssp
      summary: Query links between user groups and CID groups. At least one of CID
        group ID or user group ID should also be provided. Role ID is optional.
      operationId: queryRoles
      security:
        - oauth2:
            - mssp:read
  /mssp/queries/user-group-members/v1:
    get:
      tags:
        - mssp
      summary: Query User Group member by User UUID.
      operationId: queryUserGroupMembers
      security:
        - oauth2:
            - mssp:read
  /mssp/queries/user-groups/v1:
    get:
      tags:
        - mssp
      summary: Query User Groups.
      operationId: queryUserGroups
      security:
        - oauth2:
            - mssp:read
  /oauth2/revoke:
    post:
      tags:
        - oauth2
      summary: Revoke a previously issued OAuth2 access token before the end of its
        standard 30-minute lifespan.
      operationId: oauth2RevokeToken
      security:
        - basicAuth: []
  /oauth2/token:
    post:
      tags:
        - oauth2
      summary: Generate an OAuth2 access token
      operationId: oauth2AccessToken
  /overwatch-dashboards/aggregates/detections-global-counts/v1:
    get:
      tags:
        - Overwatch Dashboard
      summary: Get the total number of detections pushed across all customers
      operationId: AggregatesDetectionsGlobalCounts
      security:
        - oauth2:
            - overwatch-dashboard:read
  /overwatch-dashboards/aggregates/events-collections/GET/v1:
    post:
      tags:
        - Overwatch Dashboard
      summary: Get OverWatch detection event collection info by providing an aggregate
        query
      operationId: AggregatesEventsCollections
      security:
        - oauth2:
            - overwatch-dashboard:read
  /overwatch-dashboards/aggregates/events/GET/v1:
    post:
      tags:
        - Overwatch Dashboard
      summary: Get aggregate OverWatch detection event info by providing an aggregate
        query
      operationId: AggregatesEvents
      security:
        - oauth2:
            - overwatch-dashboard:read
  /overwatch-dashboards/aggregates/incidents-global-counts/v1:
    get:
      tags:
        - Overwatch Dashboard
      summary: Get the total number of incidents pushed across all customers
      operationId: AggregatesIncidentsGlobalCounts
      security:
        - oauth2:
            - overwatch-dashboard:read
  /overwatch-dashboards/aggregates/ow-events-global-counts/v1:
    get:
      tags:
        - Overwatch Dashboard
      summary: Get the total number of OverWatch events across all customers
      operationId: AggregatesOWEventsGlobalCounts
      security:
        - oauth2:
            - overwatch-dashboard:read
  /policy/combined/device-control-members/v1:
    get:
      tags:
        - device-control-policies
      summary: Search for members of a Device Control Policy in your environment by
        providing an FQL filter and paging details. Returns a set of host details
        which match the filter criteria
      operationId: queryCombinedDeviceControlPolicyMembers
      security:
        - oauth2:
            - device-control-policies:read
  /policy/combined/device-control/v1:
    get:
      tags:
        - device-control-policies
      summary: Search for Device Control Policies in your environment by providing
        an FQL filter and paging details. Returns a set of Device Control Policies
        which match the filter criteria
      operationId: queryCombinedDeviceControlPolicies
      security:
        - oauth2:
            - device-control-policies:read
  /policy/combined/firewall-members/v1:
    get:
      tags:
        - firewall-policies
      summary: Search for members of a Firewall Policy in your environment by providing
        an FQL filter and paging details. Returns a set of host details which match
        the filter criteria
      operationId: queryCombinedFirewallPolicyMembers
      security:
        - oauth2:
            - firewall-management:read
  /policy/combined/firewall/v1:
    get:
      tags:
        - firewall-policies
      summary: Search for Firewall Policies in your environment by providing an FQL
        filter and paging details. Returns a set of Firewall Policies which match
        the filter criteria
      operationId: queryCombinedFirewallPolicies
      security:
        - oauth2:
            - firewall-management:read
  /policy/combined/prevention-members/v1:
    get:
      tags:
        - prevention-policies
      summary: Search for members of a Prevention Policy in your environment by providing
        an FQL filter and paging details. Returns a set of host details which match
        the filter criteria
      operationId: queryCombinedPreventionPolicyMembers
      security:
        - oauth2:
            - prevention-policies:read
  /policy/combined/prevention/v1:
    get:
      tags:
        - prevention-policies
      summary: Search for Prevention Policies in your environment by providing an
        FQL filter and paging details. Returns a set of Prevention Policies which
        match the filter criteria
      operationId: queryCombinedPreventionPolicies
      security:
        - oauth2:
            - prevention-policies:read
  /policy/combined/response-members/v1:
    get:
      tags:
        - response-policies
      summary: Search for members of a Response policy in your environment by providing
        an FQL filter and paging details. Returns a set of host details which match
        the filter criteria
      operationId: queryCombinedRTResponsePolicyMembers
      security:
        - oauth2:
            - response-policies:read
  /policy/combined/response/v1:
    get:
      tags:
        - response-policies
      summary: Search for Response Policies in your environment by providing an FQL
        filter and paging details. Returns a set of Response Policies which match
        the filter criteria
      operationId: queryCombinedRTResponsePolicies
      security:
        - oauth2:
            - response-policies:read
  /policy/combined/reveal-uninstall-token/v1:
    post:
      tags:
        - sensor-update-policies
      summary: Reveals an uninstall token for a specific device. To retrieve the bulk
        maintenance token pass the value 'MAINTENANCE' as the value for 'device_id'
      operationId: revealUninstallToken
      security:
        - oauth2:
            - sensor-update-policies:write
  /policy/combined/sensor-update-builds/v1:
    get:
      tags:
        - sensor-update-policies
      summary: Retrieve available builds for use with Sensor Update Policies
      operationId: queryCombinedSensorUpdateBuilds
      security:
        - oauth2:
            - sensor-update-policies:read
  /policy/combined/sensor-update-kernels/v1:
    get:
      tags:
        - sensor-update-policies
      summary: Retrieve kernel compatibility info for Sensor Update Builds
      operationId: queryCombinedSensorUpdateKernels
      security:
        - oauth2:
            - sensor-update-policies:read
  /policy/combined/sensor-update-members/v1:
    get:
      tags:
        - sensor-update-policies
      summary: Search for members of a Sensor Update Policy in your environment by
        providing an FQL filter and paging details. Returns a set of host details
        which match the filter criteria
      operationId: queryCombinedSensorUpdatePolicyMembers
      security:
        - oauth2:
            - sensor-update-policies:read
  /policy/combined/sensor-update/v1:
    get:
      tags:
        - sensor-update-policies
      summary: Search for Sensor Update Policies in your environment by providing
        an FQL filter and paging details. Returns a set of Sensor Update Policies
        which match the filter criteria
      operationId: queryCombinedSensorUpdatePolicies
      security:
        - oauth2:
            - sensor-update-policies:read
  /policy/combined/sensor-update/v2:
    get:
      tags:
        - sensor-update-policies
      summary: Search for Sensor Update Policies with additional support for uninstall
        protection in your environment by providing an FQL filter and paging details.
        Returns a set of Sensor Update Policies which match the filter criteria
      operationId: queryCombinedSensorUpdatePoliciesV2
      security:
        - oauth2:
            - sensor-update-policies:read
  /policy/entities/device-control-actions/v1:
    post:
      tags:
        - device-control-policies
      summary: Perform the specified action on the Device Control Policies specified
        in the request
      operationId: performDeviceControlPoliciesAction
      security:
        - oauth2:
            - device-control-policies:write
  /policy/entities/device-control-precedence/v1:
    post:
      tags:
        - device-control-policies
      summary: Sets the precedence of Device Control Policies based on the order of
        IDs specified in the request. The first ID specified will have the highest
        precedence and the last ID specified will have the lowest. You must specify
        all non-Default Policies for a platform when updating precedence
      operationId: setDeviceControlPoliciesPrecedence
      security:
        - oauth2:
            - device-control-policies:write
  /policy/entities/device-control/v1:
    get:
      tags:
        - device-control-policies
      summary: Retrieve a set of Device Control Policies by specifying their IDs
      operationId: getDeviceControlPolicies
      security:
        - oauth2:
            - device-control-policies:read
    post:
      tags:
        - device-control-policies
      summary: Create Device Control Policies by specifying details about the policy
        to create
      operationId: createDeviceControlPolicies
      security:
        - oauth2:
            - device-control-policies:write
    delete:
      tags:
        - device-control-policies
      summary: Delete a set of Device Control Policies by specifying their IDs
      operationId: deleteDeviceControlPolicies
      security:
        - oauth2:
            - device-control-policies:write
    patch:
      tags:
        - device-control-policies
      summary: Update Device Control Policies by specifying the ID of the policy and
        details to update
      operationId: updateDeviceControlPolicies
      security:
        - oauth2:
            - device-control-policies:write
  /policy/entities/firewall-actions/v1:
    post:
      tags:
        - firewall-policies
      summary: Perform the specified action on the Firewall Policies specified in
        the request
      operationId: performFirewallPoliciesAction
      security:
        - oauth2:
            - firewall-management:write
  /policy/entities/firewall-precedence/v1:
    post:
      tags:
        - firewall-policies
      summary: Sets the precedence of Firewall Policies based on the order of IDs
        specified in the request. The first ID specified will have the highest precedence
        and the last ID specified will have the lowest. You must specify all non-Default
        Policies for a platform when updating precedence
      operationId: setFirewallPoliciesPrecedence
      security:
        - oauth2:
            - firewall-management:write
  /policy/entities/firewall/v1:
    get:
      tags:
        - firewall-policies
      summary: Retrieve a set of Firewall Policies by specifying their IDs
      operationId: getFirewallPolicies
      security:
        - oauth2:
            - firewall-management:read
    post:
      tags:
        - firewall-policies
      summary: Create Firewall Policies by specifying details about the policy to
        create
      operationId: createFirewallPolicies
      security:
        - oauth2:
            - firewall-management:write
    delete:
      tags:
        - firewall-policies
      summary: Delete a set of Firewall Policies by specifying their IDs
      operationId: deleteFirewallPolicies
      security:
        - oauth2:
            - firewall-management:write
    patch:
      tags:
        - firewall-policies
      summary: Update Firewall Policies by specifying the ID of the policy and details
        to update
      operationId: updateFirewallPolicies
      security:
        - oauth2:
            - firewall-management:write
  /policy/entities/ioa-exclusions/v1:
    get:
      tags:
        - ioa-exclusions
      summary: Get a set of IOA Exclusions by specifying their IDs
      operationId: getIOAExclusionsV1
      security:
        - oauth2:
            - self-service-ioa-exclusions:read
    post:
      tags:
        - ioa-exclusions
      summary: Create the IOA exclusions
      operationId: createIOAExclusionsV1
      security:
        - oauth2:
            - self-service-ioa-exclusions:write
    delete:
      tags:
        - ioa-exclusions
      summary: Delete the IOA exclusions by id
      operationId: deleteIOAExclusionsV1
      security:
        - oauth2:
            - self-service-ioa-exclusions:write
    patch:
      tags:
        - ioa-exclusions
      summary: Update the IOA exclusions
      operationId: updateIOAExclusionsV1
      security:
        - oauth2:
            - self-service-ioa-exclusions:write
  /policy/entities/ml-exclusions/v1:
    get:
      tags:
        - ml-exclusions
      summary: Get a set of ML Exclusions by specifying their IDs
      operationId: getMLExclusionsV1
      security:
        - oauth2:
            - ml-exclusions:read
    post:
      tags:
        - ml-exclusions
      summary: Create the ML exclusions
      operationId: createMLExclusionsV1
      security:
        - oauth2:
            - ml-exclusions:write
    delete:
      tags:
        - ml-exclusions
      summary: Delete the ML exclusions by id
      operationId: deleteMLExclusionsV1
      security:
        - oauth2:
            - ml-exclusions:write
    patch:
      tags:
        - ml-exclusions
      summary: Update the ML exclusions
      operationId: updateMLExclusionsV1
      security:
        - oauth2:
            - ml-exclusions:write
  /policy/entities/prevention-actions/v1:
    post:
      tags:
        - prevention-policies
      summary: Perform the specified action on the Prevention Policies specified in
        the request
      operationId: performPreventionPoliciesAction
      security:
        - oauth2:
            - prevention-policies:write
  /policy/entities/prevention-precedence/v1:
    post:
      tags:
        - prevention-policies
      summary: Sets the precedence of Prevention Policies based on the order of IDs
        specified in the request. The first ID specified will have the highest precedence
        and the last ID specified will have the lowest. You must specify all non-Default
        Policies for a platform when updating precedence
      operationId: setPreventionPoliciesPrecedence
      security:
        - oauth2:
            - prevention-policies:write
  /policy/entities/prevention/v1:
    get:
      tags:
        - prevention-policies
      summary: Retrieve a set of Prevention Policies by specifying their IDs
      operationId: getPreventionPolicies
      security:
        - oauth2:
            - prevention-policies:read
    post:
      tags:
        - prevention-policies
      summary: Create Prevention Policies by specifying details about the policy to
        create
      operationId: createPreventionPolicies
      security:
        - oauth2:
            - prevention-policies:write
    delete:
      tags:
        - prevention-policies
      summary: Delete a set of Prevention Policies by specifying their IDs
      operationId: deletePreventionPolicies
      security:
        - oauth2:
            - prevention-policies:write
    patch:
      tags:
        - prevention-policies
      summary: Update Prevention Policies by specifying the ID of the policy and details
        to update
      operationId: updatePreventionPolicies
      security:
        - oauth2:
            - prevention-policies:write
  /policy/entities/response-actions/v1:
    post:
      tags:
        - response-policies
      summary: Perform the specified action on the Response Policies specified in
        the request
      operationId: performRTResponsePoliciesAction
      security:
        - oauth2:
            - response-policies:write
  /policy/entities/response-precedence/v1:
    post:
      tags:
        - response-policies
      summary: Sets the precedence of Response Policies based on the order of IDs
        specified in the request. The first ID specified will have the highest precedence
        and the last ID specified will have the lowest. You must specify all non-Default
        Policies for a platform when updating precedence
      operationId: setRTResponsePoliciesPrecedence
      security:
        - oauth2:
            - response-policies:write
  /policy/entities/response/v1:
    get:
      tags:
        - response-policies
      summary: Retrieve a set of Response Policies by specifying their IDs
      operationId: getRTResponsePolicies
      security:
        - oauth2:
            - response-policies:read
    post:
      tags:
        - response-policies
      summary: Create Response Policies by specifying details about the policy to
        create
      operationId: createRTResponsePolicies
      security:
        - oauth2:
            - response-policies:write
    delete:
      tags:
        - response-policies
      summary: Delete a set of Response Policies by specifying their IDs
      operationId: deleteRTResponsePolicies
      security:
        - oauth2:
            - response-policies:write
    patch:
      tags:
        - response-policies
      summary: Update Response Policies by specifying the ID of the policy and details
        to update
      operationId: updateRTResponsePolicies
      security:
        - oauth2:
            - response-policies:write
  /policy/entities/sensor-update-actions/v1:
    post:
      tags:
        - sensor-update-policies
      summary: Perform the specified action on the Sensor Update Policies specified
        in the request
      operationId: performSensorUpdatePoliciesAction
      security:
        - oauth2:
            - sensor-update-policies:write
  /policy/entities/sensor-update-precedence/v1:
    post:
      tags:
        - sensor-update-policies
      summary: Sets the precedence of Sensor Update Policies based on the order of
        IDs specified in the request. The first ID specified will have the highest
        precedence and the last ID specified will have the lowest. You must specify
        all non-Default Policies for a platform when updating precedence
      operationId: setSensorUpdatePoliciesPrecedence
      security:
        - oauth2:
            - sensor-update-policies:write
  /policy/entities/sensor-update/v1:
    get:
      tags:
        - sensor-update-policies
      summary: Retrieve a set of Sensor Update Policies by specifying their IDs
      operationId: getSensorUpdatePolicies
      security:
        - oauth2:
            - sensor-update-policies:read
    post:
      tags:
        - sensor-update-policies
      summary: Create Sensor Update Policies by specifying details about the policy
        to create
      operationId: createSensorUpdatePolicies
      security:
        - oauth2:
            - sensor-update-policies:write
    delete:
      tags:
        - sensor-update-policies
      summary: Delete a set of Sensor Update Policies by specifying their IDs
      operationId: deleteSensorUpdatePolicies
      security:
        - oauth2:
            - sensor-update-policies:write
    patch:
      tags:
        - sensor-update-policies
      summary: Update Sensor Update Policies by specifying the ID of the policy and
        details to update
      operationId: updateSensorUpdatePolicies
      security:
        - oauth2:
            - sensor-update-policies:write
  /policy/entities/sensor-update/v2:
    get:
      tags:
        - sensor-update-policies
      summary: Retrieve a set of Sensor Update Policies with additional support for
        uninstall protection by specifying their IDs
      operationId: getSensorUpdatePoliciesV2
      security:
        - oauth2:
            - sensor-update-policies:read
    post:
      tags:
        - sensor-update-policies
      summary: Create Sensor Update Policies by specifying details about the policy
        to create with additional support for uninstall protection
      operationId: createSensorUpdatePoliciesV2
      security:
        - oauth2:
            - sensor-update-policies:write
    patch:
      tags:
        - sensor-update-policies
      summary: Update Sensor Update Policies by specifying the ID of the policy and
        details to update with additional support for uninstall protection
      operationId: updateSensorUpdatePoliciesV2
      security:
        - oauth2:
            - sensor-update-policies:write
  /policy/entities/sv-exclusions/v1:
    get:
      tags:
        - sensor-visibility-exclusions
      summary: Get a set of Sensor Visibility Exclusions by specifying their IDs
      operationId: getSensorVisibilityExclusionsV1
      security:
        - oauth2:
            - sensor-visibility-exclusions:read
    post:
      tags:
        - sensor-visibility-exclusions
      summary: Create the sensor visibility exclusions
      operationId: createSVExclusionsV1
      security:
        - oauth2:
            - sensor-visibility-exclusions:write
    delete:
      tags:
        - sensor-visibility-exclusions
      summary: Delete the sensor visibility exclusions by id
      operationId: deleteSensorVisibilityExclusionsV1
      security:
        - oauth2:
            - sensor-visibility-exclusions:write
    patch:
      tags:
        - sensor-visibility-exclusions
      summary: Update the sensor visibility exclusions
      operationId: updateSensorVisibilityExclusionsV1
      security:
        - oauth2:
            - sensor-visibility-exclusions:write
  /policy/queries/device-control-members/v1:
    get:
      tags:
        - device-control-policies
      summary: Search for members of a Device Control Policy in your environment by
        providing an FQL filter and paging details. Returns a set of Agent IDs which
        match the filter criteria
      operationId: queryDeviceControlPolicyMembers
      security:
        - oauth2:
            - device-control-policies:read
  /policy/queries/device-control/v1:
    get:
      tags:
        - device-control-policies
      summary: Search for Device Control Policies in your environment by providing
        an FQL filter and paging details. Returns a set of Device Control Policy IDs
        which match the filter criteria
      operationId: queryDeviceControlPolicies
      security:
        - oauth2:
            - device-control-policies:read
  /policy/queries/firewall-members/v1:
    get:
      tags:
        - firewall-policies
      summary: Search for members of a Firewall Policy in your environment by providing
        an FQL filter and paging details. Returns a set of Agent IDs which match the
        filter criteria
      operationId: queryFirewallPolicyMembers
      security:
        - oauth2:
            - firewall-management:read
  /policy/queries/firewall/v1:
    get:
      tags:
        - firewall-policies
      summary: Search for Firewall Policies in your environment by providing an FQL
        filter and paging details. Returns a set of Firewall Policy IDs which match
        the filter criteria
      operationId: queryFirewallPolicies
      security:
        - oauth2:
            - firewall-management:read
  /policy/queries/ioa-exclusions/v1:
    get:
      tags:
        - ioa-exclusions
      summary: Search for IOA exclusions.
      operationId: queryIOAExclusionsV1
      security:
        - oauth2:
            - self-service-ioa-exclusions:read
  /policy/queries/ml-exclusions/v1:
    get:
      tags:
        - ml-exclusions
      summary: Search for ML exclusions.
      operationId: queryMLExclusionsV1
      security:
        - oauth2:
            - ml-exclusions:read
  /policy/queries/prevention-members/v1:
    get:
      tags:
        - prevention-policies
      summary: Search for members of a Prevention Policy in your environment by providing
        an FQL filter and paging details. Returns a set of Agent IDs which match the
        filter criteria
      operationId: queryPreventionPolicyMembers
      security:
        - oauth2:
            - prevention-policies:read
  /policy/queries/prevention/v1:
    get:
      tags:
        - prevention-policies
      summary: Search for Prevention Policies in your environment by providing an
        FQL filter and paging details. Returns a set of Prevention Policy IDs which
        match the filter criteria
      operationId: queryPreventionPolicies
      security:
        - oauth2:
            - prevention-policies:read
  /policy/queries/response-members/v1:
    get:
      tags:
        - response-policies
      summary: Search for members of a Response policy in your environment by providing
        an FQL filter and paging details. Returns a set of Agent IDs which match the
        filter criteria
      operationId: queryRTResponsePolicyMembers
      security:
        - oauth2:
            - response-policies:read
  /policy/queries/response/v1:
    get:
      tags:
        - response-policies
      summary: Search for Response Policies in your environment by providing an FQL
        filter with sort and/or paging details. This returns a set of Response Policy
        IDs that match the given criteria.
      operationId: queryRTResponsePolicies
      security:
        - oauth2:
            - response-policies:read
  /policy/queries/sensor-update-kernels/{distinct-field}/v1:
    get:
      tags:
        - sensor-update-policies
      summary: Retrieve kernel compatibility info for Sensor Update Builds
      operationId: querySensorUpdateKernelsDistinct
      security:
        - oauth2:
            - sensor-update-policies:read
  /policy/queries/sensor-update-members/v1:
    get:
      tags:
        - sensor-update-policies
      summary: Search for members of a Sensor Update Policy in your environment by
        providing an FQL filter and paging details. Returns a set of Agent IDs which
        match the filter criteria
      operationId: querySensorUpdatePolicyMembers
      security:
        - oauth2:
            - sensor-update-policies:read
  /policy/queries/sensor-update/v1:
    get:
      tags:
        - sensor-update-policies
      summary: Search for Sensor Update Policies in your environment by providing
        an FQL filter and paging details. Returns a set of Sensor Update Policy IDs
        which match the filter criteria
      operationId: querySensorUpdatePolicies
      security:
        - oauth2:
            - sensor-update-policies:read
  /policy/queries/sv-exclusions/v1:
    get:
      tags:
        - sensor-visibility-exclusions
      summary: Search for sensor visibility exclusions.
      operationId: querySensorVisibilityExclusionsV1
      security:
        - oauth2:
            - sensor-visibility-exclusions:read
  /processes/entities/processes/v1:
    get:
      tags:
        - iocs
      summary: For the provided ProcessID retrieve the process details
      operationId: entities.processes
      security:
        - oauth2:
            - iocs:read
  /quarantine/aggregates/action-update-count/v1:
    get:
      tags:
        - quarantine
      summary: Returns count of potentially affected quarantined files for each action.
      operationId: ActionUpdateCount
      security:
        - oauth2:
            - quarantine:read
  /quarantine/aggregates/quarantined-files/GET/v1:
    post:
      tags:
        - quarantine
      summary: Get quarantine file aggregates as specified via json in request body.
      operationId: GetAggregateFiles
      security:
        - oauth2:
            - quarantine:read
  /quarantine/entities/quarantined-files/GET/v1:
    post:
      tags:
        - quarantine
      summary: Get quarantine file metadata for specified ids.
      operationId: GetQuarantineFiles
      security:
        - oauth2:
            - quarantine:read
  /quarantine/entities/quarantined-files/v1:
    patch:
      tags:
        - quarantine
      summary: Apply action by quarantine file ids
      operationId: UpdateQuarantinedDetectsByIds
      security:
        - oauth2:
            - quarantine:write
  /quarantine/queries/quarantined-files/v1:
    get:
      tags:
        - quarantine
      summary: Get quarantine file ids that match the provided filter criteria.
      operationId: QueryQuarantineFiles
      security:
        - oauth2:
            - quarantine:read
    patch:
      tags:
        - quarantine
      summary: Apply quarantine file actions by query.
      operationId: UpdateQfByQuery
      security:
        - oauth2:
            - quarantine:write
  /real-time-response/aggregates/sessions/GET/v1:
    post:
      tags:
        - real-time-response
      summary: Get aggregates on session data.
      operationId: RTR-AggregateSessions
      security:
        - oauth2:
            - real-time-response:read
  /real-time-response/combined/batch-active-responder-command/v1:
    post:
      tags:
        - real-time-response
      summary: Batch executes a RTR active-responder command across the hosts mapped
        to the given batch ID.
      operationId: BatchActiveResponderCmd
      security:
        - oauth2:
            - real-time-response:write
  /real-time-response/combined/batch-admin-command/v1:
    post:
      tags:
        - real-time-response-admin
      summary: Batch executes a RTR administrator command across the hosts mapped
        to the given batch ID.
      operationId: BatchAdminCmd
      security:
        - oauth2:
            - real-time-response-admin:write
  /real-time-response/combined/batch-command/v1:
    post:
      tags:
        - real-time-response
      summary: Batch executes a RTR read-only command across the hosts mapped to the
        given batch ID.
      operationId: BatchCmd
      security:
        - oauth2:
            - real-time-response:read
  /real-time-response/combined/batch-get-command/v1:
    get:
      tags:
        - real-time-response
      summary: Retrieves the status of the specified batch get command.  Will return
        successful files when they are finished processing.
      operationId: BatchGetCmdStatus
      security:
        - oauth2:
            - real-time-response:write
    post:
      tags:
        - real-time-response
      summary: Batch executes `get` command across hosts to retrieve files. After
        this call is made `GET /real-time-response/combined/batch-get-command/v1`
        is used to query for the results.
      operationId: BatchGetCmd
      security:
        - oauth2:
            - real-time-response:write
  /real-time-response/combined/batch-init-session/v1:
    post:
      tags:
        - real-time-response
      summary: Batch initialize a RTR session on multiple hosts.  Before any RTR commands
        can be used, an active session is needed on the host.
      operationId: BatchInitSessions
      security:
        - oauth2:
            - real-time-response:read
  /real-time-response/combined/batch-refresh-session/v1:
    post:
      tags:
        - real-time-response
      summary: Batch refresh a RTR session on multiple hosts. RTR sessions will expire
        after 10 minutes unless refreshed.
      operationId: BatchRefreshSessions
      security:
        - oauth2:
            - real-time-response:read
  /real-time-response/entities/active-responder-command/v1:
    get:
      tags:
        - real-time-response
      summary: Get status of an executed active-responder command on a single host.
      operationId: RTR-CheckActiveResponderCommandStatus
      security:
        - oauth2:
            - real-time-response:write
    post:
      tags:
        - real-time-response
      summary: Execute an active responder command on a single host.
      operationId: RTR-ExecuteActiveResponderCommand
      security:
        - oauth2:
            - real-time-response:write
  /real-time-response/entities/admin-command/v1:
    get:
      tags:
        - real-time-response-admin
      summary: Get status of an executed RTR administrator command on a single host.
      operationId: RTR-CheckAdminCommandStatus
      security:
        - oauth2:
            - real-time-response-admin:write
    post:
      tags:
        - real-time-response-admin
      summary: Execute a RTR administrator command on a single host.
      operationId: RTR-ExecuteAdminCommand
      security:
        - oauth2:
            - real-time-response-admin:write
  /real-time-response/entities/command/v1:
    get:
      tags:
        - real-time-response
      summary: Get status of an executed command on a single host.
      operationId: RTR-CheckCommandStatus
      security:
        - oauth2:
            - real-time-response:read
    post:
      tags:
        - real-time-response
      summary: Execute a command on a single host.
      operationId: RTR-ExecuteCommand
      security:
        - oauth2:
            - real-time-response:read
  /real-time-response/entities/extracted-file-contents/v1:
    get:
      tags:
        - real-time-response
      summary: Get RTR extracted file contents for specified session and sha256.
      operationId: RTR-GetExtractedFileContents
      security:
        - oauth2:
            - real-time-response:write
  /real-time-response/entities/file/v1:
    get:
      tags:
        - real-time-response
      summary: Get a list of files for the specified RTR session.
      operationId: RTR-ListFiles
      security:
        - oauth2:
            - real-time-response:write
    delete:
      tags:
        - real-time-response
      summary: Delete a RTR session file.
      operationId: RTR-DeleteFile
      security:
        - oauth2:
            - real-time-response:write
  /real-time-response/entities/put-files/v1:
    get:
      tags:
        - real-time-response-admin
      summary: Get put-files based on the ID's given. These are used for the RTR `put`
        command.
      operationId: RTR-GetPut-Files
      security:
        - oauth2:
            - real-time-response-admin:write
    post:
      tags:
        - real-time-response-admin
      summary: Upload a new put-file to use for the RTR `put` command.
      operationId: RTR-CreatePut-Files
      security:
        - oauth2:
            - real-time-response-admin:write
    delete:
      tags:
        - real-time-response-admin
      summary: Delete a put-file based on the ID given.  Can only delete one file
        at a time.
      operationId: RTR-DeletePut-Files
      security:
        - oauth2:
            - real-time-response-admin:write
  /real-time-response/entities/queued-sessions/GET/v1:
    post:
      tags:
        - real-time-response
      summary: Get queued session metadata by session ID.
      operationId: RTR-ListQueuedSessions
      security:
        - oauth2:
            - real-time-response:read
  /real-time-response/entities/queued-sessions/command/v1:
    delete:
      tags:
        - real-time-response
      summary: Delete a queued session command
      operationId: RTR-DeleteQueuedSession
      security:
        - oauth2:
            - real-time-response:read
  /real-time-response/entities/refresh-session/v1:
    post:
      tags:
        - real-time-response
      summary: Refresh a session timeout on a single host.
      operationId: RTR-PulseSession
      security:
        - oauth2:
            - real-time-response:read
  /real-time-response/entities/scripts/v1:
    get:
      tags:
        - real-time-response-admin
      summary: Get custom-scripts based on the ID's given. These are used for the
        RTR `runscript` command.
      operationId: RTR-GetScripts
      security:
        - oauth2:
            - real-time-response-admin:write
    post:
      tags:
        - real-time-response-admin
      summary: Upload a new custom-script to use for the RTR `runscript` command.
      operationId: RTR-CreateScripts
      security:
        - oauth2:
            - real-time-response-admin:write
    delete:
      tags:
        - real-time-response-admin
      summary: Delete a custom-script based on the ID given.  Can only delete one
        script at a time.
      operationId: RTR-DeleteScripts
      security:
        - oauth2:
            - real-time-response-admin:write
    patch:
      tags:
        - real-time-response-admin
      summary: Upload a new scripts to replace an existing one.
      operationId: RTR-UpdateScripts
      security:
        - oauth2:
            - real-time-response-admin:write
  /real-time-response/entities/sessions/GET/v1:
    post:
      tags:
        - real-time-response
      summary: Get session metadata by session id.
      operationId: RTR-ListSessions
      security:
        - oauth2:
            - real-time-response:read
  /real-time-response/entities/sessions/v1:
    post:
      tags:
        - real-time-response
      summary: Initialize a new session with the RTR cloud.
      operationId: RTR-InitSession
      security:
        - oauth2:
            - real-time-response:read
    delete:
      tags:
        - real-time-response
      summary: Delete a session.
      operationId: RTR-DeleteSession
      security:
        - oauth2:
            - real-time-response:read
  /real-time-response/queries/put-files/v1:
    get:
      tags:
        - real-time-response-admin
      summary: Get a list of put-file ID's that are available to the user for the
        `put` command.
      operationId: RTR-ListPut-Files
      security:
        - oauth2:
            - real-time-response-admin:write
  /real-time-response/queries/scripts/v1:
    get:
      tags:
        - real-time-response-admin
      summary: Get a list of custom-script ID's that are available to the user for
        the `runscript` command.
      operationId: RTR-ListScripts
      security:
        - oauth2:
            - real-time-response-admin:write
  /real-time-response/queries/sessions/v1:
    get:
      tags:
        - real-time-response
      summary: Get a list of session_ids.
      operationId: RTR-ListAllSessions
      security:
        - oauth2:
            - real-time-response:read
  /recon/aggregates/notifications/GET/v1:
    post:
      tags:
        - recon
      summary: Get notification aggregates as specified via JSON in request body.
      operationId: AggregateNotificationsV1
      security:
        - oauth2:
            - recon-monitoring-rules:read
  /recon/aggregates/rules-preview/GET/v1:
    post:
      tags:
        - recon
      summary: 'Preview rules notification count and distribution. This will return
        aggregations on: channel, count, site.'
      operationId: PreviewRuleV1
      security:
        - oauth2:
            - recon-monitoring-rules:read
  /recon/entities/actions/v1:
    get:
      tags:
        - recon
      summary: Get actions based on their IDs. IDs can be retrieved using the GET
        /queries/actions/v1 endpoint.
      operationId: GetActionsV1
      security:
        - oauth2:
            - recon-monitoring-rules:read
    post:
      tags:
        - recon
      summary: Create actions for a monitoring rule. Accepts a list of actions that
        will be attached to the monitoring rule.
      operationId: CreateActionsV1
      security:
        - oauth2:
            - recon-monitoring-rules:write
    delete:
      tags:
        - recon
      summary: Delete an action from a monitoring rule based on the action ID.
      operationId: DeleteActionV1
      security:
        - oauth2:
            - recon-monitoring-rules:write
    patch:
      tags:
        - recon
      summary: Update an action for a monitoring rule.
      operationId: UpdateActionV1
      security:
        - oauth2:
            - recon-monitoring-rules:write
  /recon/entities/notifications-detailed-translated/v1:
    get:
      tags:
        - recon
      summary: Get detailed notifications based on their IDs. These include the raw
        intelligence content that generated the match.This endpoint will return translated
        notification content. The only target language available is English. A single
        notification can be translated per request
      operationId: GetNotificationsDetailedTranslatedV1
      security:
        - oauth2:
            - recon-monitoring-rules:read
  /recon/entities/notifications-detailed/v1:
    get:
      tags:
        - recon
      summary: Get detailed notifications based on their IDs. These include the raw
        intelligence content that generated the match.
      operationId: GetNotificationsDetailedV1
      security:
        - oauth2:
            - recon-monitoring-rules:read
  /recon/entities/notifications-translated/v1:
    get:
      tags:
        - recon
      summary: Get notifications based on their IDs. IDs can be retrieved using the
        GET /queries/notifications/v1 endpoint. This endpoint will return translated
        notification content. The only target language available is English.
      operationId: GetNotificationsTranslatedV1
      security:
        - oauth2:
            - recon-monitoring-rules:read
  /recon/entities/notifications/v1:
    get:
      tags:
        - recon
      summary: Get notifications based on their IDs. IDs can be retrieved using the
        GET /queries/notifications/v1 endpoint.
      operationId: GetNotificationsV1
      security:
        - oauth2:
            - recon-monitoring-rules:read
    delete:
      tags:
        - recon
      summary: Delete notifications based on IDs. Notifications cannot be recovered
        after they are deleted.
      operationId: DeleteNotificationsV1
      security:
        - oauth2:
            - recon-monitoring-rules:write
    patch:
      tags:
        - recon
      summary: Update notification status or assignee. Accepts bulk requests
      operationId: UpdateNotificationsV1
      security:
        - oauth2:
            - recon-monitoring-rules:write
  /recon/entities/rules/v1:
    get:
      tags:
        - recon
      summary: Get monitoring rules rules by provided IDs.
      operationId: GetRulesV1
      security:
        - oauth2:
            - recon-monitoring-rules:read
    post:
      tags:
        - recon
      summary: Create monitoring rules.
      operationId: CreateRulesV1
      security:
        - oauth2:
            - recon-monitoring-rules:write
    delete:
      tags:
        - recon
      summary: Delete monitoring rules.
      operationId: DeleteRulesV1
      security:
        - oauth2:
            - recon-monitoring-rules:write
    patch:
      tags:
        - recon
      summary: Update monitoring rules.
      operationId: UpdateRulesV1
      security:
        - oauth2:
            - recon-monitoring-rules:write
  /recon/queries/actions/v1:
    get:
      tags:
        - recon
      summary: Query actions based on provided criteria. Use the IDs from this response
        to get the action entities on GET /entities/actions/v1.
      operationId: QueryActionsV1
      security:
        - oauth2:
            - recon-monitoring-rules:read
  /recon/queries/notifications/v1:
    get:
      tags:
        - recon
      summary: Query notifications based on provided criteria. Use the IDs from this
        response to get the notification entities on GET /entities/notifications/v1
        or GET /entities/notifications-detailed/v1.
      operationId: QueryNotificationsV1
      security:
        - oauth2:
            - recon-monitoring-rules:read
  /recon/queries/rules/v1:
    get:
      tags:
        - recon
      summary: Query monitoring rules based on provided criteria. Use the IDs from
        this response to fetch the rules on /entities/rules/v1.
      operationId: QueryRulesV1
      security:
        - oauth2:
            - recon-monitoring-rules:read
  /reports/entities/report-executions-download/v1:
    get:
      tags:
        - report-executions
      summary: Get report entity download
      operationId: report-executions-download.get
      security:
        - oauth2:
            - scheduled-report:read
  /reports/entities/report-executions-retry/v1:
    post:
      tags:
        - report-executions
      summary: This endpoint will be used to retry report executions
      operationId: report-executions.retry
      security:
        - oauth2:
            - scheduled-report:read
  /reports/entities/report-executions/v1:
    get:
      tags:
        - report-executions
      summary: Retrieve report details for the provided report IDs.
      operationId: report-executions.get
      security:
        - oauth2:
            - scheduled-report:read
  /reports/entities/scheduled-reports/execution/v1:
    post:
      tags:
        - scheduled-reports
      summary: Launch scheduled reports executions for the provided report IDs.
      operationId: scheduled-reports.launch
      security:
        - oauth2:
            - scheduled-report:read
  /reports/entities/scheduled-reports/v1:
    get:
      tags:
        - scheduled-reports
      summary: Retrieve scheduled reports for the provided report IDs.
      operationId: scheduled-reports.get
      security:
        - oauth2:
            - scheduled-report:read
  /reports/queries/report-executions/v1:
    get:
      tags:
        - report-executions
      summary: Find all report execution IDs matching the query with filter
      operationId: report-executions.query
      security:
        - oauth2:
            - scheduled-report:read
  /reports/queries/scheduled-reports/v1:
    get:
      tags:
        - scheduled-reports
      summary: Find all report IDs matching the query with filter
      operationId: scheduled-reports.query
      security:
        - oauth2:
            - scheduled-report:read
  /samples/entities/samples/v2:
    get:
      tags:
        - falconx-sandbox
      summary: Retrieves the file associated with the given ID (SHA256)
      operationId: GetSampleV2
      security:
        - oauth2:
            - falconx-sandbox:read
    post:
      tags:
        - falconx-sandbox
      summary: Upload a file for sandbox analysis. After uploading, use `/falconx/entities/submissions/v1`
        to start analyzing the file.
      operationId: UploadSampleV2
      security:
        - oauth2:
            - falconx-sandbox:write
    delete:
      tags:
        - falconx-sandbox
      summary: Removes a sample, including file, meta and submissions from the collection
      operationId: DeleteSampleV2
      security:
        - oauth2:
            - falconx-sandbox:write
  /samples/entities/samples/v3:
    get:
      tags:
        - sample-uploads
      summary: Retrieves the file associated with the given ID (SHA256)
      operationId: GetSampleV3
      security:
        - oauth2:
            - samplestore:read
    post:
      tags:
        - sample-uploads
      summary: Upload a file for further cloud analysis. After uploading, call the
        specific analysis API endpoint.
      operationId: UploadSampleV3
      security:
        - oauth2:
            - samplestore:write
    delete:
      tags:
        - sample-uploads
      summary: Removes a sample, including file, meta and submissions from the collection
      operationId: DeleteSampleV3
      security:
        - oauth2:
            - samplestore:write
  /samples/queries/samples/GET/v1:
    post:
      tags:
        - falconx-sandbox
      summary: Retrieves a list with sha256 of samples that exist and customer has
        rights to access them, maximum number of accepted items is 200
      operationId: QuerySampleV1
      security:
        - oauth2:
            - falconx-sandbox:write
  /scanner/aggregates/scans/GET/v1:
    post:
      tags:
        - quick-scan
      summary: Get scans aggregations as specified via json in request body.
      operationId: GetScansAggregates
      security:
        - oauth2:
            - quick-scan:read
  /scanner/entities/scans/v1:
    get:
      tags:
        - quick-scan
      summary: Check the status of a volume scan. Time required for analysis increases
        with the number of samples in a volume but usually it should take less than
        1 minute
      operationId: GetScans
      security:
        - oauth2:
            - quick-scan:read
    post:
      tags:
        - quick-scan
      summary: Submit a volume of files for ml scanning. Time required for analysis
        increases with the number of samples in a volume but usually it should take
        less than 1 minute
      operationId: ScanSamples
      security:
        - oauth2:
            - quick-scan:write
  /scanner/queries/scans/v1:
    get:
      tags:
        - quick-scan
      summary: Find IDs for submitted scans by providing an FQL filter and paging
        details. Returns a set of volume IDs that match your criteria.
      operationId: QuerySubmissions
      security:
        - oauth2:
            - quick-scan:read
  /sensors/combined/installers/v1:
    get:
      tags:
        - sensor-download
      summary: Get sensor installer details by provided query
      operationId: GetCombinedSensorInstallersByQuery
      security:
        - oauth2:
            - sensor-installers:read
  /sensors/entities/datafeed-actions/v1/{partition}:
    post:
      tags:
        - event-streams
      summary: Refresh an active event stream. Use the URL shown in a GET /sensors/entities/datafeed/v2
        response.
      operationId: refreshActiveStreamSession
      security:
        - oauth2:
            - streaming:read
  /sensors/entities/datafeed/v2:
    get:
      tags:
        - event-streams
      summary: Discover all event streams in your environment
      operationId: listAvailableStreamsOAuth2
      security:
        - oauth2:
            - streaming:read
  /sensors/entities/download-installer/v1:
    get:
      tags:
        - sensor-download
      summary: Download sensor installer by SHA256 ID
      operationId: DownloadSensorInstallerById
      security:
        - oauth2:
            - sensor-installers:read
  /sensors/entities/installers/v1:
    get:
      tags:
        - sensor-download
      summary: Get sensor installer details by provided SHA256 IDs
      operationId: GetSensorInstallersEntities
      security:
        - oauth2:
            - sensor-installers:read
  /sensors/queries/installers/ccid/v1:
    get:
      tags:
        - sensor-download
      summary: Get CCID to use with sensor installers
      operationId: GetSensorInstallersCCIDByQuery
      security:
        - oauth2:
            - sensor-installers:read
  /sensors/queries/installers/v1:
    get:
      tags:
        - sensor-download
      summary: Get sensor installer IDs by provided query
      operationId: GetSensorInstallersByQuery
      security:
        - oauth2:
            - sensor-installers:read
  /settings/entities/policy-details/v1:
    get:
      tags:
        - cspm-registration
      summary: Given a policy ID, returns detailed policy information.
      operationId: GetCSPMPolicy
      security:
        - oauth2:
            - cspm-registration:read
  /settings/entities/policy/v1:
    get:
      tags:
        - cspm-registration
      summary: Returns information about current policy settings.
      operationId: GetCSPMPolicySettings
      security:
        - oauth2:
            - cspm-registration:read
    patch:
      tags:
        - cspm-registration
      summary: Updates a policy setting - can be used to override policy severity
        or to disable a policy entirely.
      operationId: UpdateCSPMPolicySettings
      security:
        - oauth2:
            - cspm-registration:write
  /settings/scan-schedule/v1:
    get:
      tags:
        - cspm-registration
      summary: Returns scan schedule configuration for one or more cloud platforms.
      operationId: GetCSPMScanSchedule
      security:
        - oauth2:
            - cspm-registration:read
    post:
      tags:
        - cspm-registration
      summary: Updates scan schedule configuration for one or more cloud platforms.
      operationId: UpdateCSPMScanSchedule
      security:
        - oauth2:
            - cspm-registration:write
  /spotlight/combined/vulnerabilities/v1:
    get:
      tags:
        - spotlight-vulnerabilities
      summary: Search for Vulnerabilities in your environment by providing an FQL
        filter and paging details. Returns a set of Vulnerability entities which match
        the filter criteria
      operationId: combinedQueryVulnerabilities
      security:
        - oauth2:
            - spotlight-vulnerabilities:read
  /spotlight/entities/remediations/v2:
    get:
      tags:
        - spotlight-vulnerabilities
      summary: Get details on remediation by providing one or more IDs
      operationId: getRemediationsV2
      security:
        - oauth2:
            - spotlight-vulnerabilities:read
  /spotlight/entities/vulnerabilities/v2:
    get:
      tags:
        - spotlight-vulnerabilities
      summary: Get details on vulnerabilities by providing one or more IDs
      operationId: getVulnerabilities
      security:
        - oauth2:
            - spotlight-vulnerabilities:read
  /spotlight/queries/vulnerabilities/v1:
    get:
      tags:
        - spotlight-vulnerabilities
      summary: Search for Vulnerabilities in your environment by providing an FQL
        filter and paging details. Returns a set of Vulnerability IDs which match
        the filter criteria
      operationId: queryVulnerabilities
      security:
        - oauth2:
            - spotlight-vulnerabilities:read
  /user-roles/entities/user-roles/v1:
    get:
      tags:
        - user-management
      summary: Get info about a role
      operationId: GetRoles
      security:
        - oauth2:
            - usermgmt:read
    post:
      tags:
        - user-management
      summary: Assign one or more roles to a user
      operationId: GrantUserRoleIds
      security:
        - oauth2:
            - usermgmt:write
    delete:
      tags:
        - user-management
      summary: Revoke one or more roles from a user
      operationId: RevokeUserRoleIds
      security:
        - oauth2:
            - usermgmt:write
  /user-roles/queries/user-role-ids-by-cid/v1:
    get:
      tags:
        - user-management
      summary: Show role IDs for all roles available in your customer account. For
        more information on each role, provide the role ID to `/customer/entities/roles/v1`.
      operationId: GetAvailableRoleIds
      security:
        - oauth2:
            - usermgmt:read
  /user-roles/queries/user-role-ids-by-user-uuid/v1:
    get:
      tags:
        - user-management
      summary: Show role IDs of roles assigned to a user. For more information on
        each role, provide the role ID to `/customer/entities/roles/v1`.
      operationId: GetUserRoleIds
      security:
        - oauth2:
            - usermgmt:read
  /users/entities/users/v1:
    get:
      tags:
        - user-management
      summary: Get info about a user
      operationId: RetrieveUser
      security:
        - oauth2:
            - usermgmt:read
    post:
      tags:
        - user-management
      summary: Create a new user. After creating a user, assign one or more roles
        with POST /user-roles/entities/user-roles/v1
      operationId: CreateUser
      security:
        - oauth2:
            - usermgmt:write
    delete:
      tags:
        - user-management
      summary: Delete a user permanently
      operationId: DeleteUser
      security:
        - oauth2:
            - usermgmt:write
    patch:
      tags:
        - user-management
      summary: Modify an existing user's first or last name
      operationId: UpdateUser
      security:
        - oauth2:
            - usermgmt:write
  /users/queries/emails-by-cid/v1:
    get:
      tags:
        - user-management
      summary: List the usernames (usually an email address) for all users in your
        customer account
      operationId: RetrieveEmailsByCID
      security:
        - oauth2:
            - usermgmt:read
  /users/queries/user-uuids-by-cid/v1:
    get:
      tags:
        - user-management
      summary: List user IDs for all users in your customer account. For more information
        on each user, provide the user ID to `/users/entities/user/v1`.
      operationId: RetrieveUserUUIDsByCID
      security:
        - oauth2:
            - usermgmt:read
  /users/queries/user-uuids-by-email/v1:
    get:
      tags:
        - user-management
      summary: Get a user's ID by providing a username (usually an email address)
      operationId: RetrieveUserUUID
      security:
        - oauth2:
            - usermgmt:read
  /zero-trust-assessment/entities/assessments/v1:
    get:
      tags:
        - zero-trust-assessment
      summary: Get Zero Trust Assessment data for one or more hosts by providing agent
        IDs (AID) and a customer ID (CID).
      operationId: getAssessmentV1
      security:
        - oauth2:
            - zero-trust-assessment:read
  /zero-trust-assessment/entities/audit/v1:
    get:
      tags:
        - zero-trust-assessment
      summary: Get the Zero Trust Assessment compliance report for one customer ID
        (CID).
      operationId: getComplianceV1
      security:
        - oauth2:
            - zero-trust-assessment:read
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.us-2.crowdstrike.com/oauth2/token
          scopes:
            cloud-connect-aws:read: Grants read access on cloud-connect-aws resources
            cloud-connect-aws:write: Grants write access on cloud-connect-aws resources
            cspm-registration:read: Grants read access on cspm-registration resources
            cspm-registration:write: Grants write access on cspm-registration resources
            custom-ioa:read: Grants read access on custom-ioa resources
            custom-ioa:write: Grants write access on custom-ioa resources
            d4c-registration:read: Grants read access on d4c-registration resources
            d4c-registration:write: Grants write access on d4c-registration resources
            detects:read: Grants read access on detects resources
            detects:write: Grants write access on detects resources
            device-control-policies:read: Grants read access on device-control-policies
              resources
            device-control-policies:write: Grants write access on device-control-policies
              resources
            devices:read: Grants read access on devices resources
            devices:write: Grants write access on devices resources
            discover:read: Grants read access on discover resources
            falcon-container:read: Grants read access on falcon-container resources
            falconcomplete-dashboard:read: Grants read access on falconcomplete-dashboard
              resources
            falconx-actors:read: Grants read access on falconx-actors resources
            falconx-indicators:read: Grants read access on falconx-indicators resources
            falconx-reports:read: Grants read access on falconx-reports resources
            falconx-rules:read: Grants read access on falconx-rules resources
            falconx-sandbox:read: Grants read access on falconx-sandbox resources
            falconx-sandbox:write: Grants write access on falconx-sandbox resources
            fim:read: Grants read access on fim resources
            firewall-management:read: Grants read access on firewall-management resources
            firewall-management:write: Grants write access on firewall-management
              resources
            host-group:read: Grants read access on host-group resources
            host-group:write: Grants write access on host-group resources
            identity-graphql:write: Grants write access on identity-graphql resources
            incidents:read: Grants read access on incidents resources
            incidents:write: Grants write access on incidents resources
            installation-tokens:read: Grants read access on installation-tokens resources
            installation-tokens:write: Grants write access on installation-tokens
              resources
            ioc:read: Grants read access on ioc resources
            ioc:write: Grants write access on ioc resources
            iocs:read: Grants read access on iocs resources
            kubernetes-protection:read: Grants read access on kubernetes-protection
              resources
            kubernetes-protection:write: Grants write access on kubernetes-protection
              resources
            malquery:read: Grants read access on malquery resources
            malquery:write: Grants write access on malquery resources
            message-center:read: Grants read access on message-center resources
            message-center:write: Grants write access on message-center resources
            ml-exclusions:read: Grants read access on ml-exclusions resources
            ml-exclusions:write: Grants write access on ml-exclusions resources
            mssp:read: Grants read access on mssp resources
            mssp:write: Grants write access on mssp resources
            overwatch-dashboard:read: Grants read access on overwatch-dashboard resources
            prevention-policies:read: Grants read access on prevention-policies resources
            prevention-policies:write: Grants write access on prevention-policies
              resources
            quarantine:read: Grants read access on quarantine resources
            quarantine:write: Grants write access on quarantine resources
            quick-scan:read: Grants read access on quick-scan resources
            quick-scan:write: Grants write access on quick-scan resources
            real-time-response-admin:write: Grants write access on real-time-response-admin
              resources
            real-time-response:read: Grants read access on real-time-response resources
            real-time-response:write: Grants write access on real-time-response resources
            recon-monitoring-rules:read: Grants read access on recon-monitoring-rules
              resources
            recon-monitoring-rules:write: Grants write access on recon-monitoring-rules
              resources
            response-policies:read: Grants read access on response-policies resources
            response-policies:write: Grants write access on response-policies resources
            samplestore:read: Grants read access on samplestore resources
            samplestore:write: Grants write access on samplestore resources
            scheduled-report:read: Grants read access on scheduled-report resources
            self-service-ioa-exclusions:read: Grants read access on self-service-ioa-exclusions
              resources
            self-service-ioa-exclusions:write: Grants write access on self-service-ioa-exclusions
              resources
            sensor-installers:read: Grants read access on sensor-installers resources
            sensor-update-policies:read: Grants read access on sensor-update-policies
              resources
            sensor-update-policies:write: Grants write access on sensor-update-policies
              resources
            sensor-visibility-exclusions:read: Grants read access on sensor-visibility-exclusions
              resources
            sensor-visibility-exclusions:write: Grants write access on sensor-visibility-exclusions
              resources
            spotlight-vulnerabilities:read: Grants read access on spotlight-vulnerabilities
              resources
            streaming:read: Grants read access on streaming resources
            usermgmt:read: Grants read access on usermgmt resources
            usermgmt:write: Grants write access on usermgmt resources
            zero-trust-assessment:read: Grants read access on zero-trust-assessment
              resources