name: "http"
description: "Blink HTTP plugin"
tags:
  - http
  - network
  - blink

provider: "blink"
connection_types:
  basic-auth:
    reference: basic-auth
  bearer-token:
    reference: bearer-token
is_connection_optional: true
